package diacritics

import (
	"golang.org/x/text/transform"
	"golang.org/x/text/unicode/norm"
	"unicode/utf8"
)

// AsciiFoldTransformer is a Unicode stream transformer object
// which replaces a character with the ASCII folding version of the character.
var AsciiFoldTransformer = transform.Chain(
	norm.NFKC,
	&asciiFoldSpanningTransformer{},
)

type asciiFoldSpanningTransformer struct {
	transform.NopResetter
}

func (t *asciiFoldSpanningTransformer) Transform(dst, src []byte, atEOF bool) (nDst, nSrc int, err error) {
	for r, size := rune(0), 0; nSrc < len(src); {
		// Attempt to decode the current rune
		if r = rune(src[nSrc]); r < utf8.RuneSelf {
			size = 1
		} else if r, size = utf8.DecodeRune(src[nSrc:]); size == 1 {
			// Invalid rune
			if !atEOF && !utf8.FullRune(src[nSrc:]) {
				err = transform.ErrShortSrc
				break
			}
		}
		if target, ok := AsciiFoldTranslateTable[r]; ok {
			// Copy target characters if capacity allows
			targetBytes := []byte(target)
			targetSize := len(targetBytes)
			if nDst+targetSize > len(dst) {
				err = transform.ErrShortDst
				break
			}
			for i := 0; i < targetSize; i++ {
				dst[nDst] = targetBytes[i]
				nDst++
			}
			nSrc += size
		} else {
			// Verbatim copy of the source character if capacity allows
			if nDst+size > len(dst) {
				err = transform.ErrShortDst
				break
			}
			for i := 0; i < size; i++ {
				dst[nDst] = src[nSrc]
				nDst++
				nSrc++
			}
		}
	}
	return
}

func (t *asciiFoldSpanningTransformer) Span(src []byte, atEOF bool) (n int, err error) {
	for r, size := rune(0), 0; n < len(src); {
		// Attempt to decode the current rune
		if r = rune(src[n]); r < utf8.RuneSelf {
			size = 1
		} else if r, size = utf8.DecodeRune(src[n:]); size == 1 {
			// Invalid rune
			if !atEOF && !utf8.FullRune(src[n:]) {
				err = transform.ErrShortSrc
			} else {
				err = transform.ErrEndOfSpan
			}
			break
		}
		if _, ok := AsciiFoldTranslateTable[r]; ok {
			err = transform.ErrEndOfSpan
			break
		}
		n += size
	}
	return
}

// ASCII folding database fetched from
// https://github.com/apache/lucene-solr/blob/master/lucene/analysis/common/src/java/org/apache/lucene/analysis/miscellaneous/ASCIIFoldingFilter.java
var AsciiFoldTranslateTable = map[rune]string{
	'\u00c0': "A",    // À  [LATIN CAPITAL LETTER A WITH GRAVE]
	'\u00c1': "A",    // Á  [LATIN CAPITAL LETTER A WITH ACUTE]
	'\u00c2': "A",    // Â  [LATIN CAPITAL LETTER A WITH CIRCUMFLEX]
	'\u00c3': "A",    // Ã  [LATIN CAPITAL LETTER A WITH TILDE]
	'\u00c4': "A",    // Ä  [LATIN CAPITAL LETTER A WITH DIAERESIS]
	'\u00c5': "A",    // Å  [LATIN CAPITAL LETTER A WITH RING ABOVE]
	'\u0100': "A",    // Ā  [LATIN CAPITAL LETTER A WITH MACRON]
	'\u0102': "A",    // Ă  [LATIN CAPITAL LETTER A WITH BREVE]
	'\u0104': "A",    // Ą  [LATIN CAPITAL LETTER A WITH OGONEK]
	'\u018f': "A",    // Ə  http://en.wikipedia.org/wiki/Schwa  [LATIN CAPITAL LETTER SCHWA]
	'\u01cd': "A",    // Ǎ  [LATIN CAPITAL LETTER A WITH CARON]
	'\u01de': "A",    // Ǟ  [LATIN CAPITAL LETTER A WITH DIAERESIS AND MACRON]
	'\u01e0': "A",    // Ǡ  [LATIN CAPITAL LETTER A WITH DOT ABOVE AND MACRON]
	'\u01fa': "A",    // Ǻ  [LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE]
	'\u0200': "A",    // Ȁ  [LATIN CAPITAL LETTER A WITH DOUBLE GRAVE]
	'\u0202': "A",    // Ȃ  [LATIN CAPITAL LETTER A WITH INVERTED BREVE]
	'\u0226': "A",    // Ȧ  [LATIN CAPITAL LETTER A WITH DOT ABOVE]
	'\u023a': "A",    // Ⱥ  [LATIN CAPITAL LETTER A WITH STROKE]
	'\u1d00': "A",    // ᴀ  [LATIN LETTER SMALL CAPITAL A]
	'\u1e00': "A",    // Ḁ  [LATIN CAPITAL LETTER A WITH RING BELOW]
	'\u1ea0': "A",    // Ạ  [LATIN CAPITAL LETTER A WITH DOT BELOW]
	'\u1ea2': "A",    // Ả  [LATIN CAPITAL LETTER A WITH HOOK ABOVE]
	'\u1ea4': "A",    // Ấ  [LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND ACUTE]
	'\u1ea6': "A",    // Ầ  [LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND GRAVE]
	'\u1ea8': "A",    // Ẩ  [LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE]
	'\u1eaa': "A",    // Ẫ  [LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND TILDE]
	'\u1eac': "A",    // Ậ  [LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND DOT BELOW]
	'\u1eae': "A",    // Ắ  [LATIN CAPITAL LETTER A WITH BREVE AND ACUTE]
	'\u1eb0': "A",    // Ằ  [LATIN CAPITAL LETTER A WITH BREVE AND GRAVE]
	'\u1eb2': "A",    // Ẳ  [LATIN CAPITAL LETTER A WITH BREVE AND HOOK ABOVE]
	'\u1eb4': "A",    // Ẵ  [LATIN CAPITAL LETTER A WITH BREVE AND TILDE]
	'\u1eb6': "A",    // Ặ  [LATIN CAPITAL LETTER A WITH BREVE AND DOT BELOW]
	'\u24b6': "A",    // Ⓐ  [CIRCLED LATIN CAPITAL LETTER A]
	'\uff21': "A",    // Ａ  [FULLWIDTH LATIN CAPITAL LETTER A]
	'\u00e0': "a",    // à  [LATIN SMALL LETTER A WITH GRAVE]
	'\u00e1': "a",    // á  [LATIN SMALL LETTER A WITH ACUTE]
	'\u00e2': "a",    // â  [LATIN SMALL LETTER A WITH CIRCUMFLEX]
	'\u00e3': "a",    // ã  [LATIN SMALL LETTER A WITH TILDE]
	'\u00e4': "a",    // ä  [LATIN SMALL LETTER A WITH DIAERESIS]
	'\u00e5': "a",    // å  [LATIN SMALL LETTER A WITH RING ABOVE]
	'\u0101': "a",    // ā  [LATIN SMALL LETTER A WITH MACRON]
	'\u0103': "a",    // ă  [LATIN SMALL LETTER A WITH BREVE]
	'\u0105': "a",    // ą  [LATIN SMALL LETTER A WITH OGONEK]
	'\u01ce': "a",    // ǎ  [LATIN SMALL LETTER A WITH CARON]
	'\u01df': "a",    // ǟ  [LATIN SMALL LETTER A WITH DIAERESIS AND MACRON]
	'\u01e1': "a",    // ǡ  [LATIN SMALL LETTER A WITH DOT ABOVE AND MACRON]
	'\u01fb': "a",    // ǻ  [LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE]
	'\u0201': "a",    // ȁ  [LATIN SMALL LETTER A WITH DOUBLE GRAVE]
	'\u0203': "a",    // ȃ  [LATIN SMALL LETTER A WITH INVERTED BREVE]
	'\u0227': "a",    // ȧ  [LATIN SMALL LETTER A WITH DOT ABOVE]
	'\u0250': "a",    // ɐ  [LATIN SMALL LETTER TURNED A]
	'\u0259': "a",    // ə  [LATIN SMALL LETTER SCHWA]
	'\u025a': "a",    // ɚ  [LATIN SMALL LETTER SCHWA WITH HOOK]
	'\u1d8f': "a",    // ᶏ  [LATIN SMALL LETTER A WITH RETROFLEX HOOK]
	'\u1d95': "a",    // ᶕ  [LATIN SMALL LETTER SCHWA WITH RETROFLEX HOOK]
	'\u1e01': "a",    // ạ  [LATIN SMALL LETTER A WITH RING BELOW]
	'\u1e9a': "a",    // ả  [LATIN SMALL LETTER A WITH RIGHT HALF RING]
	'\u1ea1': "a",    // ạ  [LATIN SMALL LETTER A WITH DOT BELOW]
	'\u1ea3': "a",    // ả  [LATIN SMALL LETTER A WITH HOOK ABOVE]
	'\u1ea5': "a",    // ấ  [LATIN SMALL LETTER A WITH CIRCUMFLEX AND ACUTE]
	'\u1ea7': "a",    // ầ  [LATIN SMALL LETTER A WITH CIRCUMFLEX AND GRAVE]
	'\u1ea9': "a",    // ẩ  [LATIN SMALL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE]
	'\u1eab': "a",    // ẫ  [LATIN SMALL LETTER A WITH CIRCUMFLEX AND TILDE]
	'\u1ead': "a",    // ậ  [LATIN SMALL LETTER A WITH CIRCUMFLEX AND DOT BELOW]
	'\u1eaf': "a",    // ắ  [LATIN SMALL LETTER A WITH BREVE AND ACUTE]
	'\u1eb1': "a",    // ằ  [LATIN SMALL LETTER A WITH BREVE AND GRAVE]
	'\u1eb3': "a",    // ẳ  [LATIN SMALL LETTER A WITH BREVE AND HOOK ABOVE]
	'\u1eb5': "a",    // ẵ  [LATIN SMALL LETTER A WITH BREVE AND TILDE]
	'\u1eb7': "a",    // ặ  [LATIN SMALL LETTER A WITH BREVE AND DOT BELOW]
	'\u2090': "a",    // ₐ  [LATIN SUBSCRIPT SMALL LETTER A]
	'\u2094': "a",    // ₔ  [LATIN SUBSCRIPT SMALL LETTER SCHWA]
	'\u24d0': "a",    // ⓐ  [CIRCLED LATIN SMALL LETTER A]
	'\u2c65': "a",    // ⱥ  [LATIN SMALL LETTER A WITH STROKE]
	'\u2c6f': "a",    // Ɐ  [LATIN CAPITAL LETTER TURNED A]
	'\uff41': "a",    // ａ  [FULLWIDTH LATIN SMALL LETTER A]
	'\ua732': "AA",   // Ꜳ  [LATIN CAPITAL LETTER AA]
	'\u00c6': "AE",   // Æ  [LATIN CAPITAL LETTER AE]
	'\u01e2': "AE",   // Ǣ  [LATIN CAPITAL LETTER AE WITH MACRON]
	'\u01fc': "AE",   // Ǽ  [LATIN CAPITAL LETTER AE WITH ACUTE]
	'\u1d01': "AE",   // ᴁ  [LATIN LETTER SMALL CAPITAL AE]
	'\ua734': "AO",   // Ꜵ  [LATIN CAPITAL LETTER AO]
	'\ua736': "AU",   // Ꜷ  [LATIN CAPITAL LETTER AU]
	'\ua738': "AV",   // Ꜹ  [LATIN CAPITAL LETTER AV]
	'\ua73a': "AV",   // Ꜻ  [LATIN CAPITAL LETTER AV WITH HORIZONTAL BAR]
	'\ua73c': "AY",   // Ꜽ  [LATIN CAPITAL LETTER AY]
	'\u249c': "(a)",  // ⒜  [PARENTHESIZED LATIN SMALL LETTER A]
	'\ua733': "aa",   // ꜳ  [LATIN SMALL LETTER AA]
	'\u00e6': "ae",   // æ  [LATIN SMALL LETTER AE]
	'\u01e3': "ae",   // ǣ  [LATIN SMALL LETTER AE WITH MACRON]
	'\u01fd': "ae",   // ǽ  [LATIN SMALL LETTER AE WITH ACUTE]
	'\u1d02': "ae",   // ᴂ  [LATIN SMALL LETTER TURNED AE]
	'\ua735': "ao",   // ꜵ  [LATIN SMALL LETTER AO]
	'\ua737': "au",   // ꜷ  [LATIN SMALL LETTER AU]
	'\ua739': "av",   // ꜹ  [LATIN SMALL LETTER AV]
	'\ua73b': "av",   // ꜻ  [LATIN SMALL LETTER AV WITH HORIZONTAL BAR]
	'\ua73d': "ay",   // ꜽ  [LATIN SMALL LETTER AY]
	'\u0181': "B",    // Ɓ  [LATIN CAPITAL LETTER B WITH HOOK]
	'\u0182': "B",    // Ƃ  [LATIN CAPITAL LETTER B WITH TOPBAR]
	'\u0243': "B",    // Ƀ  [LATIN CAPITAL LETTER B WITH STROKE]
	'\u0299': "B",    // ʙ  [LATIN LETTER SMALL CAPITAL B]
	'\u1d03': "B",    // ᴃ  [LATIN LETTER SMALL CAPITAL BARRED B]
	'\u1e02': "B",    // Ḃ  [LATIN CAPITAL LETTER B WITH DOT ABOVE]
	'\u1e04': "B",    // Ḅ  [LATIN CAPITAL LETTER B WITH DOT BELOW]
	'\u1e06': "B",    // Ḇ  [LATIN CAPITAL LETTER B WITH LINE BELOW]
	'\u24b7': "B",    // Ⓑ  [CIRCLED LATIN CAPITAL LETTER B]
	'\uff22': "B",    // Ｂ  [FULLWIDTH LATIN CAPITAL LETTER B]
	'\u0180': "b",    // ƀ  [LATIN SMALL LETTER B WITH STROKE]
	'\u0183': "b",    // ƃ  [LATIN SMALL LETTER B WITH TOPBAR]
	'\u0253': "b",    // ɓ  [LATIN SMALL LETTER B WITH HOOK]
	'\u1d6c': "b",    // ᵬ  [LATIN SMALL LETTER B WITH MIDDLE TILDE]
	'\u1d80': "b",    // ᶀ  [LATIN SMALL LETTER B WITH PALATAL HOOK]
	'\u1e03': "b",    // ḃ  [LATIN SMALL LETTER B WITH DOT ABOVE]
	'\u1e05': "b",    // ḅ  [LATIN SMALL LETTER B WITH DOT BELOW]
	'\u1e07': "b",    // ḇ  [LATIN SMALL LETTER B WITH LINE BELOW]
	'\u24d1': "b",    // ⓑ  [CIRCLED LATIN SMALL LETTER B]
	'\uff42': "b",    // ｂ  [FULLWIDTH LATIN SMALL LETTER B]
	'\u249d': "(b)",  // ⒝  [PARENTHESIZED LATIN SMALL LETTER B]
	'\u00c7': "C",    // Ç  [LATIN CAPITAL LETTER C WITH CEDILLA]
	'\u0106': "C",    // Ć  [LATIN CAPITAL LETTER C WITH ACUTE]
	'\u0108': "C",    // Ĉ  [LATIN CAPITAL LETTER C WITH CIRCUMFLEX]
	'\u010a': "C",    // Ċ  [LATIN CAPITAL LETTER C WITH DOT ABOVE]
	'\u010c': "C",    // Č  [LATIN CAPITAL LETTER C WITH CARON]
	'\u0187': "C",    // Ƈ  [LATIN CAPITAL LETTER C WITH HOOK]
	'\u023b': "C",    // Ȼ  [LATIN CAPITAL LETTER C WITH STROKE]
	'\u0297': "C",    // ʗ  [LATIN LETTER STRETCHED C]
	'\u1d04': "C",    // ᴄ  [LATIN LETTER SMALL CAPITAL C]
	'\u1e08': "C",    // Ḉ  [LATIN CAPITAL LETTER C WITH CEDILLA AND ACUTE]
	'\u24b8': "C",    // Ⓒ  [CIRCLED LATIN CAPITAL LETTER C]
	'\uff23': "C",    // Ｃ  [FULLWIDTH LATIN CAPITAL LETTER C]
	'\u00e7': "c",    // ç  [LATIN SMALL LETTER C WITH CEDILLA]
	'\u0107': "c",    // ć  [LATIN SMALL LETTER C WITH ACUTE]
	'\u0109': "c",    // ĉ  [LATIN SMALL LETTER C WITH CIRCUMFLEX]
	'\u010b': "c",    // ċ  [LATIN SMALL LETTER C WITH DOT ABOVE]
	'\u010d': "c",    // č  [LATIN SMALL LETTER C WITH CARON]
	'\u0188': "c",    // ƈ  [LATIN SMALL LETTER C WITH HOOK]
	'\u023c': "c",    // ȼ  [LATIN SMALL LETTER C WITH STROKE]
	'\u0255': "c",    // ɕ  [LATIN SMALL LETTER C WITH CURL]
	'\u1e09': "c",    // ḉ  [LATIN SMALL LETTER C WITH CEDILLA AND ACUTE]
	'\u2184': "c",    // ↄ  [LATIN SMALL LETTER REVERSED C]
	'\u24d2': "c",    // ⓒ  [CIRCLED LATIN SMALL LETTER C]
	'\ua73e': "c",    // Ꜿ  [LATIN CAPITAL LETTER REVERSED C WITH DOT]
	'\ua73f': "c",    // ꜿ  [LATIN SMALL LETTER REVERSED C WITH DOT]
	'\uff43': "c",    // ｃ  [FULLWIDTH LATIN SMALL LETTER C]
	'\u249e': "(c)",  // ⒞  [PARENTHESIZED LATIN SMALL LETTER C]
	'\u00d0': "D",    // Ð  [LATIN CAPITAL LETTER ETH]
	'\u010e': "D",    // Ď  [LATIN CAPITAL LETTER D WITH CARON]
	'\u0110': "D",    // Đ  [LATIN CAPITAL LETTER D WITH STROKE]
	'\u0189': "D",    // Ɖ  [LATIN CAPITAL LETTER AFRICAN D]
	'\u018a': "D",    // Ɗ  [LATIN CAPITAL LETTER D WITH HOOK]
	'\u018b': "D",    // Ƌ  [LATIN CAPITAL LETTER D WITH TOPBAR]
	'\u1d05': "D",    // ᴅ  [LATIN LETTER SMALL CAPITAL D]
	'\u1d06': "D",    // ᴆ  [LATIN LETTER SMALL CAPITAL ETH]
	'\u1e0a': "D",    // Ḋ  [LATIN CAPITAL LETTER D WITH DOT ABOVE]
	'\u1e0c': "D",    // Ḍ  [LATIN CAPITAL LETTER D WITH DOT BELOW]
	'\u1e0e': "D",    // Ḏ  [LATIN CAPITAL LETTER D WITH LINE BELOW]
	'\u1e10': "D",    // Ḑ  [LATIN CAPITAL LETTER D WITH CEDILLA]
	'\u1e12': "D",    // Ḓ  [LATIN CAPITAL LETTER D WITH CIRCUMFLEX BELOW]
	'\u24b9': "D",    // Ⓓ  [CIRCLED LATIN CAPITAL LETTER D]
	'\ua779': "D",    // Ꝺ  [LATIN CAPITAL LETTER INSULAR D]
	'\uff24': "D",    // Ｄ  [FULLWIDTH LATIN CAPITAL LETTER D]
	'\u00f0': "d",    // ð  [LATIN SMALL LETTER ETH]
	'\u010f': "d",    // ď  [LATIN SMALL LETTER D WITH CARON]
	'\u0111': "d",    // đ  [LATIN SMALL LETTER D WITH STROKE]
	'\u018c': "d",    // ƌ  [LATIN SMALL LETTER D WITH TOPBAR]
	'\u0221': "d",    // ȡ  [LATIN SMALL LETTER D WITH CURL]
	'\u0256': "d",    // ɖ  [LATIN SMALL LETTER D WITH TAIL]
	'\u0257': "d",    // ɗ  [LATIN SMALL LETTER D WITH HOOK]
	'\u1d6d': "d",    // ᵭ  [LATIN SMALL LETTER D WITH MIDDLE TILDE]
	'\u1d81': "d",    // ᶁ  [LATIN SMALL LETTER D WITH PALATAL HOOK]
	'\u1d91': "d",    // ᶑ  [LATIN SMALL LETTER D WITH HOOK AND TAIL]
	'\u1e0b': "d",    // ḋ  [LATIN SMALL LETTER D WITH DOT ABOVE]
	'\u1e0d': "d",    // ḍ  [LATIN SMALL LETTER D WITH DOT BELOW]
	'\u1e0f': "d",    // ḏ  [LATIN SMALL LETTER D WITH LINE BELOW]
	'\u1e11': "d",    // ḑ  [LATIN SMALL LETTER D WITH CEDILLA]
	'\u1e13': "d",    // ḓ  [LATIN SMALL LETTER D WITH CIRCUMFLEX BELOW]
	'\u24d3': "d",    // ⓓ  [CIRCLED LATIN SMALL LETTER D]
	'\ua77a': "d",    // ꝺ  [LATIN SMALL LETTER INSULAR D]
	'\uff44': "d",    // ｄ  [FULLWIDTH LATIN SMALL LETTER D]
	'\u01c4': "DZ",   // Ǆ  [LATIN CAPITAL LETTER DZ WITH CARON]
	'\u01f1': "DZ",   // Ǳ  [LATIN CAPITAL LETTER DZ]
	'\u01c5': "Dz",   // ǅ  [LATIN CAPITAL LETTER D WITH SMALL LETTER Z WITH CARON]
	'\u01f2': "Dz",   // ǲ  [LATIN CAPITAL LETTER D WITH SMALL LETTER Z]
	'\u249f': "(d)",  // ⒟  [PARENTHESIZED LATIN SMALL LETTER D]
	'\u0238': "db",   // ȸ  [LATIN SMALL LETTER DB DIGRAPH]
	'\u01c6': "dz",   // ǆ  [LATIN SMALL LETTER DZ WITH CARON]
	'\u01f3': "dz",   // ǳ  [LATIN SMALL LETTER DZ]
	'\u02a3': "dz",   // ʣ  [LATIN SMALL LETTER DZ DIGRAPH]
	'\u02a5': "dz",   // ʥ  [LATIN SMALL LETTER DZ DIGRAPH WITH CURL]
	'\u00c8': "E",    // È  [LATIN CAPITAL LETTER E WITH GRAVE]
	'\u00c9': "E",    // É  [LATIN CAPITAL LETTER E WITH ACUTE]
	'\u00ca': "E",    // Ê  [LATIN CAPITAL LETTER E WITH CIRCUMFLEX]
	'\u00cb': "E",    // Ë  [LATIN CAPITAL LETTER E WITH DIAERESIS]
	'\u0112': "E",    // Ē  [LATIN CAPITAL LETTER E WITH MACRON]
	'\u0114': "E",    // Ĕ  [LATIN CAPITAL LETTER E WITH BREVE]
	'\u0116': "E",    // Ė  [LATIN CAPITAL LETTER E WITH DOT ABOVE]
	'\u0118': "E",    // Ę  [LATIN CAPITAL LETTER E WITH OGONEK]
	'\u011a': "E",    // Ě  [LATIN CAPITAL LETTER E WITH CARON]
	'\u018e': "E",    // Ǝ  [LATIN CAPITAL LETTER REVERSED E]
	'\u0190': "E",    // Ɛ  [LATIN CAPITAL LETTER OPEN E]
	'\u0204': "E",    // Ȅ  [LATIN CAPITAL LETTER E WITH DOUBLE GRAVE]
	'\u0206': "E",    // Ȇ  [LATIN CAPITAL LETTER E WITH INVERTED BREVE]
	'\u0228': "E",    // Ȩ  [LATIN CAPITAL LETTER E WITH CEDILLA]
	'\u0246': "E",    // Ɇ  [LATIN CAPITAL LETTER E WITH STROKE]
	'\u1d07': "E",    // ᴇ  [LATIN LETTER SMALL CAPITAL E]
	'\u1e14': "E",    // Ḕ  [LATIN CAPITAL LETTER E WITH MACRON AND GRAVE]
	'\u1e16': "E",    // Ḗ  [LATIN CAPITAL LETTER E WITH MACRON AND ACUTE]
	'\u1e18': "E",    // Ḙ  [LATIN CAPITAL LETTER E WITH CIRCUMFLEX BELOW]
	'\u1e1a': "E",    // Ḛ  [LATIN CAPITAL LETTER E WITH TILDE BELOW]
	'\u1e1c': "E",    // Ḝ  [LATIN CAPITAL LETTER E WITH CEDILLA AND BREVE]
	'\u1eb8': "E",    // Ẹ  [LATIN CAPITAL LETTER E WITH DOT BELOW]
	'\u1eba': "E",    // Ẻ  [LATIN CAPITAL LETTER E WITH HOOK ABOVE]
	'\u1ebc': "E",    // Ẽ  [LATIN CAPITAL LETTER E WITH TILDE]
	'\u1ebe': "E",    // Ế  [LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND ACUTE]
	'\u1ec0': "E",    // Ề  [LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND GRAVE]
	'\u1ec2': "E",    // Ể  [LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE]
	'\u1ec4': "E",    // Ễ  [LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND TILDE]
	'\u1ec6': "E",    // Ệ  [LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND DOT BELOW]
	'\u24ba': "E",    // Ⓔ  [CIRCLED LATIN CAPITAL LETTER E]
	'\u2c7b': "E",    // ⱻ  [LATIN LETTER SMALL CAPITAL TURNED E]
	'\uff25': "E",    // Ｅ  [FULLWIDTH LATIN CAPITAL LETTER E]
	'\u00e8': "e",    // è  [LATIN SMALL LETTER E WITH GRAVE]
	'\u00e9': "e",    // é  [LATIN SMALL LETTER E WITH ACUTE]
	'\u00ea': "e",    // ê  [LATIN SMALL LETTER E WITH CIRCUMFLEX]
	'\u00eb': "e",    // ë  [LATIN SMALL LETTER E WITH DIAERESIS]
	'\u0113': "e",    // ē  [LATIN SMALL LETTER E WITH MACRON]
	'\u0115': "e",    // ĕ  [LATIN SMALL LETTER E WITH BREVE]
	'\u0117': "e",    // ė  [LATIN SMALL LETTER E WITH DOT ABOVE]
	'\u0119': "e",    // ę  [LATIN SMALL LETTER E WITH OGONEK]
	'\u011b': "e",    // ě  [LATIN SMALL LETTER E WITH CARON]
	'\u01dd': "e",    // ǝ  [LATIN SMALL LETTER TURNED E]
	'\u0205': "e",    // ȅ  [LATIN SMALL LETTER E WITH DOUBLE GRAVE]
	'\u0207': "e",    // ȇ  [LATIN SMALL LETTER E WITH INVERTED BREVE]
	'\u0229': "e",    // ȩ  [LATIN SMALL LETTER E WITH CEDILLA]
	'\u0247': "e",    // ɇ  [LATIN SMALL LETTER E WITH STROKE]
	'\u0258': "e",    // ɘ  [LATIN SMALL LETTER REVERSED E]
	'\u025b': "e",    // ɛ  [LATIN SMALL LETTER OPEN E]
	'\u025c': "e",    // ɜ  [LATIN SMALL LETTER REVERSED OPEN E]
	'\u025d': "e",    // ɝ  [LATIN SMALL LETTER REVERSED OPEN E WITH HOOK]
	'\u025e': "e",    // ɞ  [LATIN SMALL LETTER CLOSED REVERSED OPEN E]
	'\u029a': "e",    // ʚ  [LATIN SMALL LETTER CLOSED OPEN E]
	'\u1d08': "e",    // ᴈ  [LATIN SMALL LETTER TURNED OPEN E]
	'\u1d92': "e",    // ᶒ  [LATIN SMALL LETTER E WITH RETROFLEX HOOK]
	'\u1d93': "e",    // ᶓ  [LATIN SMALL LETTER OPEN E WITH RETROFLEX HOOK]
	'\u1d94': "e",    // ᶔ  [LATIN SMALL LETTER REVERSED OPEN E WITH RETROFLEX HOOK]
	'\u1e15': "e",    // ḕ  [LATIN SMALL LETTER E WITH MACRON AND GRAVE]
	'\u1e17': "e",    // ḗ  [LATIN SMALL LETTER E WITH MACRON AND ACUTE]
	'\u1e19': "e",    // ḙ  [LATIN SMALL LETTER E WITH CIRCUMFLEX BELOW]
	'\u1e1b': "e",    // ḛ  [LATIN SMALL LETTER E WITH TILDE BELOW]
	'\u1e1d': "e",    // ḝ  [LATIN SMALL LETTER E WITH CEDILLA AND BREVE]
	'\u1eb9': "e",    // ẹ  [LATIN SMALL LETTER E WITH DOT BELOW]
	'\u1ebb': "e",    // ẻ  [LATIN SMALL LETTER E WITH HOOK ABOVE]
	'\u1ebd': "e",    // ẽ  [LATIN SMALL LETTER E WITH TILDE]
	'\u1ebf': "e",    // ế  [LATIN SMALL LETTER E WITH CIRCUMFLEX AND ACUTE]
	'\u1ec1': "e",    // ề  [LATIN SMALL LETTER E WITH CIRCUMFLEX AND GRAVE]
	'\u1ec3': "e",    // ể  [LATIN SMALL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE]
	'\u1ec5': "e",    // ễ  [LATIN SMALL LETTER E WITH CIRCUMFLEX AND TILDE]
	'\u1ec7': "e",    // ệ  [LATIN SMALL LETTER E WITH CIRCUMFLEX AND DOT BELOW]
	'\u2091': "e",    // ₑ  [LATIN SUBSCRIPT SMALL LETTER E]
	'\u24d4': "e",    // ⓔ  [CIRCLED LATIN SMALL LETTER E]
	'\u2c78': "e",    // ⱸ  [LATIN SMALL LETTER E WITH NOTCH]
	'\uff45': "e",    // ｅ  [FULLWIDTH LATIN SMALL LETTER E]
	'\u24a0': "(e)",  // ⒠  [PARENTHESIZED LATIN SMALL LETTER E]
	'\u0191': "F",    // Ƒ  [LATIN CAPITAL LETTER F WITH HOOK]
	'\u1e1e': "F",    // Ḟ  [LATIN CAPITAL LETTER F WITH DOT ABOVE]
	'\u24bb': "F",    // Ⓕ  [CIRCLED LATIN CAPITAL LETTER F]
	'\ua730': "F",    // ꜰ  [LATIN LETTER SMALL CAPITAL F]
	'\ua77b': "F",    // Ꝼ  [LATIN CAPITAL LETTER INSULAR F]
	'\ua7fb': "F",    // ꟻ  [LATIN EPIGRAPHIC LETTER REVERSED F]
	'\uff26': "F",    // Ｆ  [FULLWIDTH LATIN CAPITAL LETTER F]
	'\u0192': "f",    // ƒ  [LATIN SMALL LETTER F WITH HOOK]
	'\u1d6e': "f",    // ᵮ  [LATIN SMALL LETTER F WITH MIDDLE TILDE]
	'\u1d82': "f",    // ᶂ  [LATIN SMALL LETTER F WITH PALATAL HOOK]
	'\u1e1f': "f",    // ḟ  [LATIN SMALL LETTER F WITH DOT ABOVE]
	'\u1e9b': "f",    // ẛ  [LATIN SMALL LETTER LONG S WITH DOT ABOVE]
	'\u24d5': "f",    // ⓕ  [CIRCLED LATIN SMALL LETTER F]
	'\ua77c': "f",    // ꝼ  [LATIN SMALL LETTER INSULAR F]
	'\uff46': "f",    // ｆ  [FULLWIDTH LATIN SMALL LETTER F]
	'\u24a1': "(f)",  // ⒡  [PARENTHESIZED LATIN SMALL LETTER F]
	'\ufb00': "ff",   // ﬀ  [LATIN SMALL LIGATURE FF]
	'\ufb03': "ffi",  // ﬃ  [LATIN SMALL LIGATURE FFI]
	'\ufb04': "ffl",  // ﬄ  [LATIN SMALL LIGATURE FFL]
	'\ufb01': "fi",   // ﬁ  [LATIN SMALL LIGATURE FI]
	'\ufb02': "fl",   // ﬂ  [LATIN SMALL LIGATURE FL]
	'\u011c': "G",    // Ĝ  [LATIN CAPITAL LETTER G WITH CIRCUMFLEX]
	'\u011e': "G",    // Ğ  [LATIN CAPITAL LETTER G WITH BREVE]
	'\u0120': "G",    // Ġ  [LATIN CAPITAL LETTER G WITH DOT ABOVE]
	'\u0122': "G",    // Ģ  [LATIN CAPITAL LETTER G WITH CEDILLA]
	'\u0193': "G",    // Ɠ  [LATIN CAPITAL LETTER G WITH HOOK]
	'\u01e4': "G",    // Ǥ  [LATIN CAPITAL LETTER G WITH STROKE]
	'\u01e5': "G",    // ǥ  [LATIN SMALL LETTER G WITH STROKE]
	'\u01e6': "G",    // Ǧ  [LATIN CAPITAL LETTER G WITH CARON]
	'\u01e7': "G",    // ǧ  [LATIN SMALL LETTER G WITH CARON]
	'\u01f4': "G",    // Ǵ  [LATIN CAPITAL LETTER G WITH ACUTE]
	'\u0262': "G",    // ɢ  [LATIN LETTER SMALL CAPITAL G]
	'\u029b': "G",    // ʛ  [LATIN LETTER SMALL CAPITAL G WITH HOOK]
	'\u1e20': "G",    // Ḡ  [LATIN CAPITAL LETTER G WITH MACRON]
	'\u24bc': "G",    // Ⓖ  [CIRCLED LATIN CAPITAL LETTER G]
	'\ua77d': "G",    // Ᵹ  [LATIN CAPITAL LETTER INSULAR G]
	'\ua77e': "G",    // Ꝿ  [LATIN CAPITAL LETTER TURNED INSULAR G]
	'\uff27': "G",    // Ｇ  [FULLWIDTH LATIN CAPITAL LETTER G]
	'\u011d': "g",    // ĝ  [LATIN SMALL LETTER G WITH CIRCUMFLEX]
	'\u011f': "g",    // ğ  [LATIN SMALL LETTER G WITH BREVE]
	'\u0121': "g",    // ġ  [LATIN SMALL LETTER G WITH DOT ABOVE]
	'\u0123': "g",    // ģ  [LATIN SMALL LETTER G WITH CEDILLA]
	'\u01f5': "g",    // ǵ  [LATIN SMALL LETTER G WITH ACUTE]
	'\u0260': "g",    // ɠ  [LATIN SMALL LETTER G WITH HOOK]
	'\u0261': "g",    // ɡ  [LATIN SMALL LETTER SCRIPT G]
	'\u1d77': "g",    // ᵷ  [LATIN SMALL LETTER TURNED G]
	'\u1d79': "g",    // ᵹ  [LATIN SMALL LETTER INSULAR G]
	'\u1d83': "g",    // ᶃ  [LATIN SMALL LETTER G WITH PALATAL HOOK]
	'\u1e21': "g",    // ḡ  [LATIN SMALL LETTER G WITH MACRON]
	'\u24d6': "g",    // ⓖ  [CIRCLED LATIN SMALL LETTER G]
	'\ua77f': "g",    // ꝿ  [LATIN SMALL LETTER TURNED INSULAR G]
	'\uff47': "g",    // ｇ  [FULLWIDTH LATIN SMALL LETTER G]
	'\u24a2': "(g)",  // ⒢  [PARENTHESIZED LATIN SMALL LETTER G]
	'\u0124': "H",    // Ĥ  [LATIN CAPITAL LETTER H WITH CIRCUMFLEX]
	'\u0126': "H",    // Ħ  [LATIN CAPITAL LETTER H WITH STROKE]
	'\u021e': "H",    // Ȟ  [LATIN CAPITAL LETTER H WITH CARON]
	'\u029c': "H",    // ʜ  [LATIN LETTER SMALL CAPITAL H]
	'\u1e22': "H",    // Ḣ  [LATIN CAPITAL LETTER H WITH DOT ABOVE]
	'\u1e24': "H",    // Ḥ  [LATIN CAPITAL LETTER H WITH DOT BELOW]
	'\u1e26': "H",    // Ḧ  [LATIN CAPITAL LETTER H WITH DIAERESIS]
	'\u1e28': "H",    // Ḩ  [LATIN CAPITAL LETTER H WITH CEDILLA]
	'\u1e2a': "H",    // Ḫ  [LATIN CAPITAL LETTER H WITH BREVE BELOW]
	'\u24bd': "H",    // Ⓗ  [CIRCLED LATIN CAPITAL LETTER H]
	'\u2c67': "H",    // Ⱨ  [LATIN CAPITAL LETTER H WITH DESCENDER]
	'\u2c75': "H",    // Ⱶ  [LATIN CAPITAL LETTER HALF H]
	'\uff28': "H",    // Ｈ  [FULLWIDTH LATIN CAPITAL LETTER H]
	'\u0125': "h",    // ĥ  [LATIN SMALL LETTER H WITH CIRCUMFLEX]
	'\u0127': "h",    // ħ  [LATIN SMALL LETTER H WITH STROKE]
	'\u021f': "h",    // ȟ  [LATIN SMALL LETTER H WITH CARON]
	'\u0265': "h",    // ɥ  [LATIN SMALL LETTER TURNED H]
	'\u0266': "h",    // ɦ  [LATIN SMALL LETTER H WITH HOOK]
	'\u02ae': "h",    // ʮ  [LATIN SMALL LETTER TURNED H WITH FISHHOOK]
	'\u02af': "h",    // ʯ  [LATIN SMALL LETTER TURNED H WITH FISHHOOK AND TAIL]
	'\u1e23': "h",    // ḣ  [LATIN SMALL LETTER H WITH DOT ABOVE]
	'\u1e25': "h",    // ḥ  [LATIN SMALL LETTER H WITH DOT BELOW]
	'\u1e27': "h",    // ḧ  [LATIN SMALL LETTER H WITH DIAERESIS]
	'\u1e29': "h",    // ḩ  [LATIN SMALL LETTER H WITH CEDILLA]
	'\u1e2b': "h",    // ḫ  [LATIN SMALL LETTER H WITH BREVE BELOW]
	'\u1e96': "h",    // ẖ  [LATIN SMALL LETTER H WITH LINE BELOW]
	'\u24d7': "h",    // ⓗ  [CIRCLED LATIN SMALL LETTER H]
	'\u2c68': "h",    // ⱨ  [LATIN SMALL LETTER H WITH DESCENDER]
	'\u2c76': "h",    // ⱶ  [LATIN SMALL LETTER HALF H]
	'\uff48': "h",    // ｈ  [FULLWIDTH LATIN SMALL LETTER H]
	'\u01f6': "HV",   // Ƕ  http://en.wikipedia.org/wiki/Hwair  [LATIN CAPITAL LETTER HWAIR]
	'\u24a3': "(h)",  // ⒣  [PARENTHESIZED LATIN SMALL LETTER H]
	'\u0195': "hv",   // ƕ  [LATIN SMALL LETTER HV]
	'\u00cc': "I",    // Ì  [LATIN CAPITAL LETTER I WITH GRAVE]
	'\u00cd': "I",    // Í  [LATIN CAPITAL LETTER I WITH ACUTE]
	'\u00ce': "I",    // Î  [LATIN CAPITAL LETTER I WITH CIRCUMFLEX]
	'\u00cf': "I",    // Ï  [LATIN CAPITAL LETTER I WITH DIAERESIS]
	'\u0128': "I",    // Ĩ  [LATIN CAPITAL LETTER I WITH TILDE]
	'\u012a': "I",    // Ī  [LATIN CAPITAL LETTER I WITH MACRON]
	'\u012c': "I",    // Ĭ  [LATIN CAPITAL LETTER I WITH BREVE]
	'\u012e': "I",    // Į  [LATIN CAPITAL LETTER I WITH OGONEK]
	'\u0130': "I",    // İ  [LATIN CAPITAL LETTER I WITH DOT ABOVE]
	'\u0196': "I",    // Ɩ  [LATIN CAPITAL LETTER IOTA]
	'\u0197': "I",    // Ɨ  [LATIN CAPITAL LETTER I WITH STROKE]
	'\u01cf': "I",    // Ǐ  [LATIN CAPITAL LETTER I WITH CARON]
	'\u0208': "I",    // Ȉ  [LATIN CAPITAL LETTER I WITH DOUBLE GRAVE]
	'\u020a': "I",    // Ȋ  [LATIN CAPITAL LETTER I WITH INVERTED BREVE]
	'\u026a': "I",    // ɪ  [LATIN LETTER SMALL CAPITAL I]
	'\u1d7b': "I",    // ᵻ  [LATIN SMALL CAPITAL LETTER I WITH STROKE]
	'\u1e2c': "I",    // Ḭ  [LATIN CAPITAL LETTER I WITH TILDE BELOW]
	'\u1e2e': "I",    // Ḯ  [LATIN CAPITAL LETTER I WITH DIAERESIS AND ACUTE]
	'\u1ec8': "I",    // Ỉ  [LATIN CAPITAL LETTER I WITH HOOK ABOVE]
	'\u1eca': "I",    // Ị  [LATIN CAPITAL LETTER I WITH DOT BELOW]
	'\u24be': "I",    // Ⓘ  [CIRCLED LATIN CAPITAL LETTER I]
	'\ua7fe': "I",    // ꟾ  [LATIN EPIGRAPHIC LETTER I LONGA]
	'\uff29': "I",    // Ｉ  [FULLWIDTH LATIN CAPITAL LETTER I]
	'\u00ec': "i",    // ì  [LATIN SMALL LETTER I WITH GRAVE]
	'\u00ed': "i",    // í  [LATIN SMALL LETTER I WITH ACUTE]
	'\u00ee': "i",    // î  [LATIN SMALL LETTER I WITH CIRCUMFLEX]
	'\u00ef': "i",    // ï  [LATIN SMALL LETTER I WITH DIAERESIS]
	'\u0129': "i",    // ĩ  [LATIN SMALL LETTER I WITH TILDE]
	'\u012b': "i",    // ī  [LATIN SMALL LETTER I WITH MACRON]
	'\u012d': "i",    // ĭ  [LATIN SMALL LETTER I WITH BREVE]
	'\u012f': "i",    // į  [LATIN SMALL LETTER I WITH OGONEK]
	'\u0131': "i",    // ı  [LATIN SMALL LETTER DOTLESS I]
	'\u01d0': "i",    // ǐ  [LATIN SMALL LETTER I WITH CARON]
	'\u0209': "i",    // ȉ  [LATIN SMALL LETTER I WITH DOUBLE GRAVE]
	'\u020b': "i",    // ȋ  [LATIN SMALL LETTER I WITH INVERTED BREVE]
	'\u0268': "i",    // ɨ  [LATIN SMALL LETTER I WITH STROKE]
	'\u1d09': "i",    // ᴉ  [LATIN SMALL LETTER TURNED I]
	'\u1d62': "i",    // ᵢ  [LATIN SUBSCRIPT SMALL LETTER I]
	'\u1d7c': "i",    // ᵼ  [LATIN SMALL LETTER IOTA WITH STROKE]
	'\u1d96': "i",    // ᶖ  [LATIN SMALL LETTER I WITH RETROFLEX HOOK]
	'\u1e2d': "i",    // ḭ  [LATIN SMALL LETTER I WITH TILDE BELOW]
	'\u1e2f': "i",    // ḯ  [LATIN SMALL LETTER I WITH DIAERESIS AND ACUTE]
	'\u1ec9': "i",    // ỉ  [LATIN SMALL LETTER I WITH HOOK ABOVE]
	'\u1ecb': "i",    // ị  [LATIN SMALL LETTER I WITH DOT BELOW]
	'\u2071': "i",    // ⁱ  [SUPERSCRIPT LATIN SMALL LETTER I]
	'\u24d8': "i",    // ⓘ  [CIRCLED LATIN SMALL LETTER I]
	'\uff49': "i",    // ｉ  [FULLWIDTH LATIN SMALL LETTER I]
	'\u0132': "IJ",   // Ĳ  [LATIN CAPITAL LIGATURE IJ]
	'\u24a4': "(i)",  // ⒤  [PARENTHESIZED LATIN SMALL LETTER I]
	'\u0133': "ij",   // ĳ  [LATIN SMALL LIGATURE IJ]
	'\u0134': "J",    // Ĵ  [LATIN CAPITAL LETTER J WITH CIRCUMFLEX]
	'\u0248': "J",    // Ɉ  [LATIN CAPITAL LETTER J WITH STROKE]
	'\u1d0a': "J",    // ᴊ  [LATIN LETTER SMALL CAPITAL J]
	'\u24bf': "J",    // Ⓙ  [CIRCLED LATIN CAPITAL LETTER J]
	'\uff2a': "J",    // Ｊ  [FULLWIDTH LATIN CAPITAL LETTER J]
	'\u0135': "j",    // ĵ  [LATIN SMALL LETTER J WITH CIRCUMFLEX]
	'\u01f0': "j",    // ǰ  [LATIN SMALL LETTER J WITH CARON]
	'\u0237': "j",    // ȷ  [LATIN SMALL LETTER DOTLESS J]
	'\u0249': "j",    // ɉ  [LATIN SMALL LETTER J WITH STROKE]
	'\u025f': "j",    // ɟ  [LATIN SMALL LETTER DOTLESS J WITH STROKE]
	'\u0284': "j",    // ʄ  [LATIN SMALL LETTER DOTLESS J WITH STROKE AND HOOK]
	'\u029d': "j",    // ʝ  [LATIN SMALL LETTER J WITH CROSSED-TAIL]
	'\u24d9': "j",    // ⓙ  [CIRCLED LATIN SMALL LETTER J]
	'\u2c7c': "j",    // ⱼ  [LATIN SUBSCRIPT SMALL LETTER J]
	'\uff4a': "j",    // ｊ  [FULLWIDTH LATIN SMALL LETTER J]
	'\u24a5': "(j)",  // ⒥  [PARENTHESIZED LATIN SMALL LETTER J]
	'\u0136': "K",    // Ķ  [LATIN CAPITAL LETTER K WITH CEDILLA]
	'\u0198': "K",    // Ƙ  [LATIN CAPITAL LETTER K WITH HOOK]
	'\u01e8': "K",    // Ǩ  [LATIN CAPITAL LETTER K WITH CARON]
	'\u1d0b': "K",    // ᴋ  [LATIN LETTER SMALL CAPITAL K]
	'\u1e30': "K",    // Ḱ  [LATIN CAPITAL LETTER K WITH ACUTE]
	'\u1e32': "K",    // Ḳ  [LATIN CAPITAL LETTER K WITH DOT BELOW]
	'\u1e34': "K",    // Ḵ  [LATIN CAPITAL LETTER K WITH LINE BELOW]
	'\u24c0': "K",    // Ⓚ  [CIRCLED LATIN CAPITAL LETTER K]
	'\u2c69': "K",    // Ⱪ  [LATIN CAPITAL LETTER K WITH DESCENDER]
	'\ua740': "K",    // Ꝁ  [LATIN CAPITAL LETTER K WITH STROKE]
	'\ua742': "K",    // Ꝃ  [LATIN CAPITAL LETTER K WITH DIAGONAL STROKE]
	'\ua744': "K",    // Ꝅ  [LATIN CAPITAL LETTER K WITH STROKE AND DIAGONAL STROKE]
	'\uff2b': "K",    // Ｋ  [FULLWIDTH LATIN CAPITAL LETTER K]
	'\u0137': "k",    // ķ  [LATIN SMALL LETTER K WITH CEDILLA]
	'\u0199': "k",    // ƙ  [LATIN SMALL LETTER K WITH HOOK]
	'\u01e9': "k",    // ǩ  [LATIN SMALL LETTER K WITH CARON]
	'\u029e': "k",    // ʞ  [LATIN SMALL LETTER TURNED K]
	'\u1d84': "k",    // ᶄ  [LATIN SMALL LETTER K WITH PALATAL HOOK]
	'\u1e31': "k",    // ḱ  [LATIN SMALL LETTER K WITH ACUTE]
	'\u1e33': "k",    // ḳ  [LATIN SMALL LETTER K WITH DOT BELOW]
	'\u1e35': "k",    // ḵ  [LATIN SMALL LETTER K WITH LINE BELOW]
	'\u24da': "k",    // ⓚ  [CIRCLED LATIN SMALL LETTER K]
	'\u2c6a': "k",    // ⱪ  [LATIN SMALL LETTER K WITH DESCENDER]
	'\ua741': "k",    // ꝁ  [LATIN SMALL LETTER K WITH STROKE]
	'\ua743': "k",    // ꝃ  [LATIN SMALL LETTER K WITH DIAGONAL STROKE]
	'\ua745': "k",    // ꝅ  [LATIN SMALL LETTER K WITH STROKE AND DIAGONAL STROKE]
	'\uff4b': "k",    // ｋ  [FULLWIDTH LATIN SMALL LETTER K]
	'\u24a6': "(k)",  // ⒦  [PARENTHESIZED LATIN SMALL LETTER K]
	'\u0139': "L",    // Ĺ  [LATIN CAPITAL LETTER L WITH ACUTE]
	'\u013b': "L",    // Ļ  [LATIN CAPITAL LETTER L WITH CEDILLA]
	'\u013d': "L",    // Ľ  [LATIN CAPITAL LETTER L WITH CARON]
	'\u013f': "L",    // Ŀ  [LATIN CAPITAL LETTER L WITH MIDDLE DOT]
	'\u0141': "L",    // Ł  [LATIN CAPITAL LETTER L WITH STROKE]
	'\u023d': "L",    // Ƚ  [LATIN CAPITAL LETTER L WITH BAR]
	'\u029f': "L",    // ʟ  [LATIN LETTER SMALL CAPITAL L]
	'\u1d0c': "L",    // ᴌ  [LATIN LETTER SMALL CAPITAL L WITH STROKE]
	'\u1e36': "L",    // Ḷ  [LATIN CAPITAL LETTER L WITH DOT BELOW]
	'\u1e38': "L",    // Ḹ  [LATIN CAPITAL LETTER L WITH DOT BELOW AND MACRON]
	'\u1e3a': "L",    // Ḻ  [LATIN CAPITAL LETTER L WITH LINE BELOW]
	'\u1e3c': "L",    // Ḽ  [LATIN CAPITAL LETTER L WITH CIRCUMFLEX BELOW]
	'\u24c1': "L",    // Ⓛ  [CIRCLED LATIN CAPITAL LETTER L]
	'\u2c60': "L",    // Ⱡ  [LATIN CAPITAL LETTER L WITH DOUBLE BAR]
	'\u2c62': "L",    // Ɫ  [LATIN CAPITAL LETTER L WITH MIDDLE TILDE]
	'\ua746': "L",    // Ꝇ  [LATIN CAPITAL LETTER BROKEN L]
	'\ua748': "L",    // Ꝉ  [LATIN CAPITAL LETTER L WITH HIGH STROKE]
	'\ua780': "L",    // Ꞁ  [LATIN CAPITAL LETTER TURNED L]
	'\uff2c': "L",    // Ｌ  [FULLWIDTH LATIN CAPITAL LETTER L]
	'\u013a': "l",    // ĺ  [LATIN SMALL LETTER L WITH ACUTE]
	'\u013c': "l",    // ļ  [LATIN SMALL LETTER L WITH CEDILLA]
	'\u013e': "l",    // ľ  [LATIN SMALL LETTER L WITH CARON]
	'\u0140': "l",    // ŀ  [LATIN SMALL LETTER L WITH MIDDLE DOT]
	'\u0142': "l",    // ł  [LATIN SMALL LETTER L WITH STROKE]
	'\u019a': "l",    // ƚ  [LATIN SMALL LETTER L WITH BAR]
	'\u0234': "l",    // ȴ  [LATIN SMALL LETTER L WITH CURL]
	'\u026b': "l",    // ɫ  [LATIN SMALL LETTER L WITH MIDDLE TILDE]
	'\u026c': "l",    // ɬ  [LATIN SMALL LETTER L WITH BELT]
	'\u026d': "l",    // ɭ  [LATIN SMALL LETTER L WITH RETROFLEX HOOK]
	'\u1d85': "l",    // ᶅ  [LATIN SMALL LETTER L WITH PALATAL HOOK]
	'\u1e37': "l",    // ḷ  [LATIN SMALL LETTER L WITH DOT BELOW]
	'\u1e39': "l",    // ḹ  [LATIN SMALL LETTER L WITH DOT BELOW AND MACRON]
	'\u1e3b': "l",    // ḻ  [LATIN SMALL LETTER L WITH LINE BELOW]
	'\u1e3d': "l",    // ḽ  [LATIN SMALL LETTER L WITH CIRCUMFLEX BELOW]
	'\u24db': "l",    // ⓛ  [CIRCLED LATIN SMALL LETTER L]
	'\u2c61': "l",    // ⱡ  [LATIN SMALL LETTER L WITH DOUBLE BAR]
	'\ua747': "l",    // ꝇ  [LATIN SMALL LETTER BROKEN L]
	'\ua749': "l",    // ꝉ  [LATIN SMALL LETTER L WITH HIGH STROKE]
	'\ua781': "l",    // ꞁ  [LATIN SMALL LETTER TURNED L]
	'\uff4c': "l",    // ｌ  [FULLWIDTH LATIN SMALL LETTER L]
	'\u01c7': "LJ",   // Ǉ  [LATIN CAPITAL LETTER LJ]
	'\u1efa': "LL",   // Ỻ  [LATIN CAPITAL LETTER MIDDLE-WELSH LL]
	'\u01c8': "Lj",   // ǈ  [LATIN CAPITAL LETTER L WITH SMALL LETTER J]
	'\u24a7': "(l)",  // ⒧  [PARENTHESIZED LATIN SMALL LETTER L]
	'\u01c9': "lj",   // ǉ  [LATIN SMALL LETTER LJ]
	'\u1efb': "ll",   // ỻ  [LATIN SMALL LETTER MIDDLE-WELSH LL]
	'\u02aa': "ls",   // ʪ  [LATIN SMALL LETTER LS DIGRAPH]
	'\u02ab': "lz",   // ʫ  [LATIN SMALL LETTER LZ DIGRAPH]
	'\u019c': "M",    // Ɯ  [LATIN CAPITAL LETTER TURNED M]
	'\u1d0d': "M",    // ᴍ  [LATIN LETTER SMALL CAPITAL M]
	'\u1e3e': "M",    // Ḿ  [LATIN CAPITAL LETTER M WITH ACUTE]
	'\u1e40': "M",    // Ṁ  [LATIN CAPITAL LETTER M WITH DOT ABOVE]
	'\u1e42': "M",    // Ṃ  [LATIN CAPITAL LETTER M WITH DOT BELOW]
	'\u24c2': "M",    // Ⓜ  [CIRCLED LATIN CAPITAL LETTER M]
	'\u2c6e': "M",    // Ɱ  [LATIN CAPITAL LETTER M WITH HOOK]
	'\ua7fd': "M",    // ꟽ  [LATIN EPIGRAPHIC LETTER INVERTED M]
	'\ua7ff': "M",    // ꟿ  [LATIN EPIGRAPHIC LETTER ARCHAIC M]
	'\uff2d': "M",    // Ｍ  [FULLWIDTH LATIN CAPITAL LETTER M]
	'\u026f': "m",    // ɯ  [LATIN SMALL LETTER TURNED M]
	'\u0270': "m",    // ɰ  [LATIN SMALL LETTER TURNED M WITH LONG LEG]
	'\u0271': "m",    // ɱ  [LATIN SMALL LETTER M WITH HOOK]
	'\u1d6f': "m",    // ᵯ  [LATIN SMALL LETTER M WITH MIDDLE TILDE]
	'\u1d86': "m",    // ᶆ  [LATIN SMALL LETTER M WITH PALATAL HOOK]
	'\u1e3f': "m",    // ḿ  [LATIN SMALL LETTER M WITH ACUTE]
	'\u1e41': "m",    // ṁ  [LATIN SMALL LETTER M WITH DOT ABOVE]
	'\u1e43': "m",    // ṃ  [LATIN SMALL LETTER M WITH DOT BELOW]
	'\u24dc': "m",    // ⓜ  [CIRCLED LATIN SMALL LETTER M]
	'\uff4d': "m",    // ｍ  [FULLWIDTH LATIN SMALL LETTER M]
	'\u24a8': "(m)",  // ⒨  [PARENTHESIZED LATIN SMALL LETTER M]
	'\u00d1': "N",    // Ñ  [LATIN CAPITAL LETTER N WITH TILDE]
	'\u0143': "N",    // Ń  [LATIN CAPITAL LETTER N WITH ACUTE]
	'\u0145': "N",    // Ņ  [LATIN CAPITAL LETTER N WITH CEDILLA]
	'\u0147': "N",    // Ň  [LATIN CAPITAL LETTER N WITH CARON]
	'\u014a': "N",    // Ŋ  http://en.wikipedia.org/wiki/Eng_(letter)  [LATIN CAPITAL LETTER ENG]
	'\u019d': "N",    // Ɲ  [LATIN CAPITAL LETTER N WITH LEFT HOOK]
	'\u01f8': "N",    // Ǹ  [LATIN CAPITAL LETTER N WITH GRAVE]
	'\u0220': "N",    // Ƞ  [LATIN CAPITAL LETTER N WITH LONG RIGHT LEG]
	'\u0274': "N",    // ɴ  [LATIN LETTER SMALL CAPITAL N]
	'\u1d0e': "N",    // ᴎ  [LATIN LETTER SMALL CAPITAL REVERSED N]
	'\u1e44': "N",    // Ṅ  [LATIN CAPITAL LETTER N WITH DOT ABOVE]
	'\u1e46': "N",    // Ṇ  [LATIN CAPITAL LETTER N WITH DOT BELOW]
	'\u1e48': "N",    // Ṉ  [LATIN CAPITAL LETTER N WITH LINE BELOW]
	'\u1e4a': "N",    // Ṋ  [LATIN CAPITAL LETTER N WITH CIRCUMFLEX BELOW]
	'\u24c3': "N",    // Ⓝ  [CIRCLED LATIN CAPITAL LETTER N]
	'\uff2e': "N",    // Ｎ  [FULLWIDTH LATIN CAPITAL LETTER N]
	'\u00f1': "n",    // ñ  [LATIN SMALL LETTER N WITH TILDE]
	'\u0144': "n",    // ń  [LATIN SMALL LETTER N WITH ACUTE]
	'\u0146': "n",    // ņ  [LATIN SMALL LETTER N WITH CEDILLA]
	'\u0148': "n",    // ň  [LATIN SMALL LETTER N WITH CARON]
	'\u0149': "n",    // ŉ  [LATIN SMALL LETTER N PRECEDED BY APOSTROPHE]
	'\u014b': "n",    // ŋ  http://en.wikipedia.org/wiki/Eng_(letter)  [LATIN SMALL LETTER ENG]
	'\u019e': "n",    // ƞ  [LATIN SMALL LETTER N WITH LONG RIGHT LEG]
	'\u01f9': "n",    // ǹ  [LATIN SMALL LETTER N WITH GRAVE]
	'\u0235': "n",    // ȵ  [LATIN SMALL LETTER N WITH CURL]
	'\u0272': "n",    // ɲ  [LATIN SMALL LETTER N WITH LEFT HOOK]
	'\u0273': "n",    // ɳ  [LATIN SMALL LETTER N WITH RETROFLEX HOOK]
	'\u1d70': "n",    // ᵰ  [LATIN SMALL LETTER N WITH MIDDLE TILDE]
	'\u1d87': "n",    // ᶇ  [LATIN SMALL LETTER N WITH PALATAL HOOK]
	'\u1e45': "n",    // ṅ  [LATIN SMALL LETTER N WITH DOT ABOVE]
	'\u1e47': "n",    // ṇ  [LATIN SMALL LETTER N WITH DOT BELOW]
	'\u1e49': "n",    // ṉ  [LATIN SMALL LETTER N WITH LINE BELOW]
	'\u1e4b': "n",    // ṋ  [LATIN SMALL LETTER N WITH CIRCUMFLEX BELOW]
	'\u207f': "n",    // ⁿ  [SUPERSCRIPT LATIN SMALL LETTER N]
	'\u24dd': "n",    // ⓝ  [CIRCLED LATIN SMALL LETTER N]
	'\uff4e': "n",    // ｎ  [FULLWIDTH LATIN SMALL LETTER N]
	'\u01ca': "NJ",   // Ǌ  [LATIN CAPITAL LETTER NJ]
	'\u01cb': "Nj",   // ǋ  [LATIN CAPITAL LETTER N WITH SMALL LETTER J]
	'\u24a9': "(n)",  // ⒩  [PARENTHESIZED LATIN SMALL LETTER N]
	'\u01cc': "nj",   // ǌ  [LATIN SMALL LETTER NJ]
	'\u00d2': "O",    // Ò  [LATIN CAPITAL LETTER O WITH GRAVE]
	'\u00d3': "O",    // Ó  [LATIN CAPITAL LETTER O WITH ACUTE]
	'\u00d4': "O",    // Ô  [LATIN CAPITAL LETTER O WITH CIRCUMFLEX]
	'\u00d5': "O",    // Õ  [LATIN CAPITAL LETTER O WITH TILDE]
	'\u00d6': "O",    // Ö  [LATIN CAPITAL LETTER O WITH DIAERESIS]
	'\u00d8': "O",    // Ø  [LATIN CAPITAL LETTER O WITH STROKE]
	'\u014c': "O",    // Ō  [LATIN CAPITAL LETTER O WITH MACRON]
	'\u014e': "O",    // Ŏ  [LATIN CAPITAL LETTER O WITH BREVE]
	'\u0150': "O",    // Ő  [LATIN CAPITAL LETTER O WITH DOUBLE ACUTE]
	'\u0186': "O",    // Ɔ  [LATIN CAPITAL LETTER OPEN O]
	'\u019f': "O",    // Ɵ  [LATIN CAPITAL LETTER O WITH MIDDLE TILDE]
	'\u01a0': "O",    // Ơ  [LATIN CAPITAL LETTER O WITH HORN]
	'\u01d1': "O",    // Ǒ  [LATIN CAPITAL LETTER O WITH CARON]
	'\u01ea': "O",    // Ǫ  [LATIN CAPITAL LETTER O WITH OGONEK]
	'\u01ec': "O",    // Ǭ  [LATIN CAPITAL LETTER O WITH OGONEK AND MACRON]
	'\u01fe': "O",    // Ǿ  [LATIN CAPITAL LETTER O WITH STROKE AND ACUTE]
	'\u020c': "O",    // Ȍ  [LATIN CAPITAL LETTER O WITH DOUBLE GRAVE]
	'\u020e': "O",    // Ȏ  [LATIN CAPITAL LETTER O WITH INVERTED BREVE]
	'\u022a': "O",    // Ȫ  [LATIN CAPITAL LETTER O WITH DIAERESIS AND MACRON]
	'\u022c': "O",    // Ȭ  [LATIN CAPITAL LETTER O WITH TILDE AND MACRON]
	'\u022e': "O",    // Ȯ  [LATIN CAPITAL LETTER O WITH DOT ABOVE]
	'\u0230': "O",    // Ȱ  [LATIN CAPITAL LETTER O WITH DOT ABOVE AND MACRON]
	'\u1d0f': "O",    // ᴏ  [LATIN LETTER SMALL CAPITAL O]
	'\u1d10': "O",    // ᴐ  [LATIN LETTER SMALL CAPITAL OPEN O]
	'\u1e4c': "O",    // Ṍ  [LATIN CAPITAL LETTER O WITH TILDE AND ACUTE]
	'\u1e4e': "O",    // Ṏ  [LATIN CAPITAL LETTER O WITH TILDE AND DIAERESIS]
	'\u1e50': "O",    // Ṑ  [LATIN CAPITAL LETTER O WITH MACRON AND GRAVE]
	'\u1e52': "O",    // Ṓ  [LATIN CAPITAL LETTER O WITH MACRON AND ACUTE]
	'\u1ecc': "O",    // Ọ  [LATIN CAPITAL LETTER O WITH DOT BELOW]
	'\u1ece': "O",    // Ỏ  [LATIN CAPITAL LETTER O WITH HOOK ABOVE]
	'\u1ed0': "O",    // Ố  [LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND ACUTE]
	'\u1ed2': "O",    // Ồ  [LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND GRAVE]
	'\u1ed4': "O",    // Ổ  [LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE]
	'\u1ed6': "O",    // Ỗ  [LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND TILDE]
	'\u1ed8': "O",    // Ộ  [LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND DOT BELOW]
	'\u1eda': "O",    // Ớ  [LATIN CAPITAL LETTER O WITH HORN AND ACUTE]
	'\u1edc': "O",    // Ờ  [LATIN CAPITAL LETTER O WITH HORN AND GRAVE]
	'\u1ede': "O",    // Ở  [LATIN CAPITAL LETTER O WITH HORN AND HOOK ABOVE]
	'\u1ee0': "O",    // Ỡ  [LATIN CAPITAL LETTER O WITH HORN AND TILDE]
	'\u1ee2': "O",    // Ợ  [LATIN CAPITAL LETTER O WITH HORN AND DOT BELOW]
	'\u24c4': "O",    // Ⓞ  [CIRCLED LATIN CAPITAL LETTER O]
	'\ua74a': "O",    // Ꝋ  [LATIN CAPITAL LETTER O WITH LONG STROKE OVERLAY]
	'\ua74c': "O",    // Ꝍ  [LATIN CAPITAL LETTER O WITH LOOP]
	'\uff2f': "O",    // Ｏ  [FULLWIDTH LATIN CAPITAL LETTER O]
	'\u00f2': "o",    // ò  [LATIN SMALL LETTER O WITH GRAVE]
	'\u00f3': "o",    // ó  [LATIN SMALL LETTER O WITH ACUTE]
	'\u00f4': "o",    // ô  [LATIN SMALL LETTER O WITH CIRCUMFLEX]
	'\u00f5': "o",    // õ  [LATIN SMALL LETTER O WITH TILDE]
	'\u00f6': "o",    // ö  [LATIN SMALL LETTER O WITH DIAERESIS]
	'\u00f8': "o",    // ø  [LATIN SMALL LETTER O WITH STROKE]
	'\u014d': "o",    // ō  [LATIN SMALL LETTER O WITH MACRON]
	'\u014f': "o",    // ŏ  [LATIN SMALL LETTER O WITH BREVE]
	'\u0151': "o",    // ő  [LATIN SMALL LETTER O WITH DOUBLE ACUTE]
	'\u01a1': "o",    // ơ  [LATIN SMALL LETTER O WITH HORN]
	'\u01d2': "o",    // ǒ  [LATIN SMALL LETTER O WITH CARON]
	'\u01eb': "o",    // ǫ  [LATIN SMALL LETTER O WITH OGONEK]
	'\u01ed': "o",    // ǭ  [LATIN SMALL LETTER O WITH OGONEK AND MACRON]
	'\u01ff': "o",    // ǿ  [LATIN SMALL LETTER O WITH STROKE AND ACUTE]
	'\u020d': "o",    // ȍ  [LATIN SMALL LETTER O WITH DOUBLE GRAVE]
	'\u020f': "o",    // ȏ  [LATIN SMALL LETTER O WITH INVERTED BREVE]
	'\u022b': "o",    // ȫ  [LATIN SMALL LETTER O WITH DIAERESIS AND MACRON]
	'\u022d': "o",    // ȭ  [LATIN SMALL LETTER O WITH TILDE AND MACRON]
	'\u022f': "o",    // ȯ  [LATIN SMALL LETTER O WITH DOT ABOVE]
	'\u0231': "o",    // ȱ  [LATIN SMALL LETTER O WITH DOT ABOVE AND MACRON]
	'\u0254': "o",    // ɔ  [LATIN SMALL LETTER OPEN O]
	'\u0275': "o",    // ɵ  [LATIN SMALL LETTER BARRED O]
	'\u1d16': "o",    // ᴖ  [LATIN SMALL LETTER TOP HALF O]
	'\u1d17': "o",    // ᴗ  [LATIN SMALL LETTER BOTTOM HALF O]
	'\u1d97': "o",    // ᶗ  [LATIN SMALL LETTER OPEN O WITH RETROFLEX HOOK]
	'\u1e4d': "o",    // ṍ  [LATIN SMALL LETTER O WITH TILDE AND ACUTE]
	'\u1e4f': "o",    // ṏ  [LATIN SMALL LETTER O WITH TILDE AND DIAERESIS]
	'\u1e51': "o",    // ṑ  [LATIN SMALL LETTER O WITH MACRON AND GRAVE]
	'\u1e53': "o",    // ṓ  [LATIN SMALL LETTER O WITH MACRON AND ACUTE]
	'\u1ecd': "o",    // ọ  [LATIN SMALL LETTER O WITH DOT BELOW]
	'\u1ecf': "o",    // ỏ  [LATIN SMALL LETTER O WITH HOOK ABOVE]
	'\u1ed1': "o",    // ố  [LATIN SMALL LETTER O WITH CIRCUMFLEX AND ACUTE]
	'\u1ed3': "o",    // ồ  [LATIN SMALL LETTER O WITH CIRCUMFLEX AND GRAVE]
	'\u1ed5': "o",    // ổ  [LATIN SMALL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE]
	'\u1ed7': "o",    // ỗ  [LATIN SMALL LETTER O WITH CIRCUMFLEX AND TILDE]
	'\u1ed9': "o",    // ộ  [LATIN SMALL LETTER O WITH CIRCUMFLEX AND DOT BELOW]
	'\u1edb': "o",    // ớ  [LATIN SMALL LETTER O WITH HORN AND ACUTE]
	'\u1edd': "o",    // ờ  [LATIN SMALL LETTER O WITH HORN AND GRAVE]
	'\u1edf': "o",    // ở  [LATIN SMALL LETTER O WITH HORN AND HOOK ABOVE]
	'\u1ee1': "o",    // ỡ  [LATIN SMALL LETTER O WITH HORN AND TILDE]
	'\u1ee3': "o",    // ợ  [LATIN SMALL LETTER O WITH HORN AND DOT BELOW]
	'\u2092': "o",    // ₒ  [LATIN SUBSCRIPT SMALL LETTER O]
	'\u24de': "o",    // ⓞ  [CIRCLED LATIN SMALL LETTER O]
	'\u2c7a': "o",    // ⱺ  [LATIN SMALL LETTER O WITH LOW RING INSIDE]
	'\ua74b': "o",    // ꝋ  [LATIN SMALL LETTER O WITH LONG STROKE OVERLAY]
	'\ua74d': "o",    // ꝍ  [LATIN SMALL LETTER O WITH LOOP]
	'\uff4f': "o",    // ｏ  [FULLWIDTH LATIN SMALL LETTER O]
	'\u0152': "OE",   // Œ  [LATIN CAPITAL LIGATURE OE]
	'\u0276': "OE",   // ɶ  [LATIN LETTER SMALL CAPITAL OE]
	'\ua74e': "OO",   // Ꝏ  [LATIN CAPITAL LETTER OO]
	'\u0222': "OU",   // Ȣ  http://en.wikipedia.org/wiki/OU  [LATIN CAPITAL LETTER OU]
	'\u1d15': "OU",   // ᴕ  [LATIN LETTER SMALL CAPITAL OU]
	'\u24aa': "(o)",  // ⒪  [PARENTHESIZED LATIN SMALL LETTER O]
	'\u0153': "oe",   // œ  [LATIN SMALL LIGATURE OE]
	'\u1d14': "oe",   // ᴔ  [LATIN SMALL LETTER TURNED OE]
	'\ua74f': "oo",   // ꝏ  [LATIN SMALL LETTER OO]
	'\u0223': "ou",   // ȣ  http://en.wikipedia.org/wiki/OU  [LATIN SMALL LETTER OU]
	'\u01a4': "P",    // Ƥ  [LATIN CAPITAL LETTER P WITH HOOK]
	'\u1d18': "P",    // ᴘ  [LATIN LETTER SMALL CAPITAL P]
	'\u1e54': "P",    // Ṕ  [LATIN CAPITAL LETTER P WITH ACUTE]
	'\u1e56': "P",    // Ṗ  [LATIN CAPITAL LETTER P WITH DOT ABOVE]
	'\u24c5': "P",    // Ⓟ  [CIRCLED LATIN CAPITAL LETTER P]
	'\u2c63': "P",    // Ᵽ  [LATIN CAPITAL LETTER P WITH STROKE]
	'\ua750': "P",    // Ꝑ  [LATIN CAPITAL LETTER P WITH STROKE THROUGH DESCENDER]
	'\ua752': "P",    // Ꝓ  [LATIN CAPITAL LETTER P WITH FLOURISH]
	'\ua754': "P",    // Ꝕ  [LATIN CAPITAL LETTER P WITH SQUIRREL TAIL]
	'\uff30': "P",    // Ｐ  [FULLWIDTH LATIN CAPITAL LETTER P]
	'\u01a5': "p",    // ƥ  [LATIN SMALL LETTER P WITH HOOK]
	'\u1d71': "p",    // ᵱ  [LATIN SMALL LETTER P WITH MIDDLE TILDE]
	'\u1d7d': "p",    // ᵽ  [LATIN SMALL LETTER P WITH STROKE]
	'\u1d88': "p",    // ᶈ  [LATIN SMALL LETTER P WITH PALATAL HOOK]
	'\u1e55': "p",    // ṕ  [LATIN SMALL LETTER P WITH ACUTE]
	'\u1e57': "p",    // ṗ  [LATIN SMALL LETTER P WITH DOT ABOVE]
	'\u24df': "p",    // ⓟ  [CIRCLED LATIN SMALL LETTER P]
	'\ua751': "p",    // ꝑ  [LATIN SMALL LETTER P WITH STROKE THROUGH DESCENDER]
	'\ua753': "p",    // ꝓ  [LATIN SMALL LETTER P WITH FLOURISH]
	'\ua755': "p",    // ꝕ  [LATIN SMALL LETTER P WITH SQUIRREL TAIL]
	'\ua7fc': "p",    // ꟼ  [LATIN EPIGRAPHIC LETTER REVERSED P]
	'\uff50': "p",    // ｐ  [FULLWIDTH LATIN SMALL LETTER P]
	'\u24ab': "(p)",  // ⒫  [PARENTHESIZED LATIN SMALL LETTER P]
	'\u024a': "Q",    // Ɋ  [LATIN CAPITAL LETTER SMALL Q WITH HOOK TAIL]
	'\u24c6': "Q",    // Ⓠ  [CIRCLED LATIN CAPITAL LETTER Q]
	'\ua756': "Q",    // Ꝗ  [LATIN CAPITAL LETTER Q WITH STROKE THROUGH DESCENDER]
	'\ua758': "Q",    // Ꝙ  [LATIN CAPITAL LETTER Q WITH DIAGONAL STROKE]
	'\uff31': "Q",    // Ｑ  [FULLWIDTH LATIN CAPITAL LETTER Q]
	'\u0138': "q",    // ĸ  http://en.wikipedia.org/wiki/Kra_(letter)  [LATIN SMALL LETTER KRA]
	'\u024b': "q",    // ɋ  [LATIN SMALL LETTER Q WITH HOOK TAIL]
	'\u02a0': "q",    // ʠ  [LATIN SMALL LETTER Q WITH HOOK]
	'\u24e0': "q",    // ⓠ  [CIRCLED LATIN SMALL LETTER Q]
	'\ua757': "q",    // ꝗ  [LATIN SMALL LETTER Q WITH STROKE THROUGH DESCENDER]
	'\ua759': "q",    // ꝙ  [LATIN SMALL LETTER Q WITH DIAGONAL STROKE]
	'\uff51': "q",    // ｑ  [FULLWIDTH LATIN SMALL LETTER Q]
	'\u24ac': "(q)",  // ⒬  [PARENTHESIZED LATIN SMALL LETTER Q]
	'\u0239': "qp",   // ȹ  [LATIN SMALL LETTER QP DIGRAPH]
	'\u0154': "R",    // Ŕ  [LATIN CAPITAL LETTER R WITH ACUTE]
	'\u0156': "R",    // Ŗ  [LATIN CAPITAL LETTER R WITH CEDILLA]
	'\u0158': "R",    // Ř  [LATIN CAPITAL LETTER R WITH CARON]
	'\u0210': "R",    // Ȓ  [LATIN CAPITAL LETTER R WITH DOUBLE GRAVE]
	'\u0212': "R",    // Ȓ  [LATIN CAPITAL LETTER R WITH INVERTED BREVE]
	'\u024c': "R",    // Ɍ  [LATIN CAPITAL LETTER R WITH STROKE]
	'\u0280': "R",    // ʀ  [LATIN LETTER SMALL CAPITAL R]
	'\u0281': "R",    // ʁ  [LATIN LETTER SMALL CAPITAL INVERTED R]
	'\u1d19': "R",    // ᴙ  [LATIN LETTER SMALL CAPITAL REVERSED R]
	'\u1d1a': "R",    // ᴚ  [LATIN LETTER SMALL CAPITAL TURNED R]
	'\u1e58': "R",    // Ṙ  [LATIN CAPITAL LETTER R WITH DOT ABOVE]
	'\u1e5a': "R",    // Ṛ  [LATIN CAPITAL LETTER R WITH DOT BELOW]
	'\u1e5c': "R",    // Ṝ  [LATIN CAPITAL LETTER R WITH DOT BELOW AND MACRON]
	'\u1e5e': "R",    // Ṟ  [LATIN CAPITAL LETTER R WITH LINE BELOW]
	'\u24c7': "R",    // Ⓡ  [CIRCLED LATIN CAPITAL LETTER R]
	'\u2c64': "R",    // Ɽ  [LATIN CAPITAL LETTER R WITH TAIL]
	'\ua75a': "R",    // Ꝛ  [LATIN CAPITAL LETTER R ROTUNDA]
	'\ua782': "R",    // Ꞃ  [LATIN CAPITAL LETTER INSULAR R]
	'\uff32': "R",    // Ｒ  [FULLWIDTH LATIN CAPITAL LETTER R]
	'\u0155': "r",    // ŕ  [LATIN SMALL LETTER R WITH ACUTE]
	'\u0157': "r",    // ŗ  [LATIN SMALL LETTER R WITH CEDILLA]
	'\u0159': "r",    // ř  [LATIN SMALL LETTER R WITH CARON]
	'\u0211': "r",    // ȑ  [LATIN SMALL LETTER R WITH DOUBLE GRAVE]
	'\u0213': "r",    // ȓ  [LATIN SMALL LETTER R WITH INVERTED BREVE]
	'\u024d': "r",    // ɍ  [LATIN SMALL LETTER R WITH STROKE]
	'\u027c': "r",    // ɼ  [LATIN SMALL LETTER R WITH LONG LEG]
	'\u027d': "r",    // ɽ  [LATIN SMALL LETTER R WITH TAIL]
	'\u027e': "r",    // ɾ  [LATIN SMALL LETTER R WITH FISHHOOK]
	'\u027f': "r",    // ɿ  [LATIN SMALL LETTER REVERSED R WITH FISHHOOK]
	'\u1d63': "r",    // ᵣ  [LATIN SUBSCRIPT SMALL LETTER R]
	'\u1d72': "r",    // ᵲ  [LATIN SMALL LETTER R WITH MIDDLE TILDE]
	'\u1d73': "r",    // ᵳ  [LATIN SMALL LETTER R WITH FISHHOOK AND MIDDLE TILDE]
	'\u1d89': "r",    // ᶉ  [LATIN SMALL LETTER R WITH PALATAL HOOK]
	'\u1e59': "r",    // ṙ  [LATIN SMALL LETTER R WITH DOT ABOVE]
	'\u1e5b': "r",    // ṛ  [LATIN SMALL LETTER R WITH DOT BELOW]
	'\u1e5d': "r",    // ṝ  [LATIN SMALL LETTER R WITH DOT BELOW AND MACRON]
	'\u1e5f': "r",    // ṟ  [LATIN SMALL LETTER R WITH LINE BELOW]
	'\u24e1': "r",    // ⓡ  [CIRCLED LATIN SMALL LETTER R]
	'\ua75b': "r",    // ꝛ  [LATIN SMALL LETTER R ROTUNDA]
	'\ua783': "r",    // ꞃ  [LATIN SMALL LETTER INSULAR R]
	'\uff52': "r",    // ｒ  [FULLWIDTH LATIN SMALL LETTER R]
	'\u24ad': "(r)",  // ⒭  [PARENTHESIZED LATIN SMALL LETTER R]
	'\u015a': "S",    // Ś  [LATIN CAPITAL LETTER S WITH ACUTE]
	'\u015c': "S",    // Ŝ  [LATIN CAPITAL LETTER S WITH CIRCUMFLEX]
	'\u015e': "S",    // Ş  [LATIN CAPITAL LETTER S WITH CEDILLA]
	'\u0160': "S",    // Š  [LATIN CAPITAL LETTER S WITH CARON]
	'\u0218': "S",    // Ș  [LATIN CAPITAL LETTER S WITH COMMA BELOW]
	'\u1e60': "S",    // Ṡ  [LATIN CAPITAL LETTER S WITH DOT ABOVE]
	'\u1e62': "S",    // Ṣ  [LATIN CAPITAL LETTER S WITH DOT BELOW]
	'\u1e64': "S",    // Ṥ  [LATIN CAPITAL LETTER S WITH ACUTE AND DOT ABOVE]
	'\u1e66': "S",    // Ṧ  [LATIN CAPITAL LETTER S WITH CARON AND DOT ABOVE]
	'\u1e68': "S",    // Ṩ  [LATIN CAPITAL LETTER S WITH DOT BELOW AND DOT ABOVE]
	'\u24c8': "S",    // Ⓢ  [CIRCLED LATIN CAPITAL LETTER S]
	'\ua731': "S",    // ꜱ  [LATIN LETTER SMALL CAPITAL S]
	'\ua785': "S",    // ꞅ  [LATIN SMALL LETTER INSULAR S]
	'\uff33': "S",    // Ｓ  [FULLWIDTH LATIN CAPITAL LETTER S]
	'\u015b': "s",    // ś  [LATIN SMALL LETTER S WITH ACUTE]
	'\u015d': "s",    // ŝ  [LATIN SMALL LETTER S WITH CIRCUMFLEX]
	'\u015f': "s",    // ş  [LATIN SMALL LETTER S WITH CEDILLA]
	'\u0161': "s",    // š  [LATIN SMALL LETTER S WITH CARON]
	'\u017f': "s",    // ſ  http://en.wikipedia.org/wiki/Long_S  [LATIN SMALL LETTER LONG S]
	'\u0219': "s",    // ș  [LATIN SMALL LETTER S WITH COMMA BELOW]
	'\u023f': "s",    // ȿ  [LATIN SMALL LETTER S WITH SWASH TAIL]
	'\u0282': "s",    // ʂ  [LATIN SMALL LETTER S WITH HOOK]
	'\u1d74': "s",    // ᵴ  [LATIN SMALL LETTER S WITH MIDDLE TILDE]
	'\u1d8a': "s",    // ᶊ  [LATIN SMALL LETTER S WITH PALATAL HOOK]
	'\u1e61': "s",    // ṡ  [LATIN SMALL LETTER S WITH DOT ABOVE]
	'\u1e63': "s",    // ṣ  [LATIN SMALL LETTER S WITH DOT BELOW]
	'\u1e65': "s",    // ṥ  [LATIN SMALL LETTER S WITH ACUTE AND DOT ABOVE]
	'\u1e67': "s",    // ṧ  [LATIN SMALL LETTER S WITH CARON AND DOT ABOVE]
	'\u1e69': "s",    // ṩ  [LATIN SMALL LETTER S WITH DOT BELOW AND DOT ABOVE]
	'\u1e9c': "s",    // ẜ  [LATIN SMALL LETTER LONG S WITH DIAGONAL STROKE]
	'\u1e9d': "s",    // ẝ  [LATIN SMALL LETTER LONG S WITH HIGH STROKE]
	'\u24e2': "s",    // ⓢ  [CIRCLED LATIN SMALL LETTER S]
	'\ua784': "s",    // Ꞅ  [LATIN CAPITAL LETTER INSULAR S]
	'\uff53': "s",    // ｓ  [FULLWIDTH LATIN SMALL LETTER S]
	'\u1e9e': "SS",   // ẞ  [LATIN CAPITAL LETTER SHARP S]
	'\u24ae': "(s)",  // ⒮  [PARENTHESIZED LATIN SMALL LETTER S]
	'\u00df': "ss",   // ß  [LATIN SMALL LETTER SHARP S]
	'\ufb06': "st",   // ﬆ  [LATIN SMALL LIGATURE ST]
	'\u0162': "T",    // Ţ  [LATIN CAPITAL LETTER T WITH CEDILLA]
	'\u0164': "T",    // Ť  [LATIN CAPITAL LETTER T WITH CARON]
	'\u0166': "T",    // Ŧ  [LATIN CAPITAL LETTER T WITH STROKE]
	'\u01ac': "T",    // Ƭ  [LATIN CAPITAL LETTER T WITH HOOK]
	'\u01ae': "T",    // Ʈ  [LATIN CAPITAL LETTER T WITH RETROFLEX HOOK]
	'\u021a': "T",    // Ț  [LATIN CAPITAL LETTER T WITH COMMA BELOW]
	'\u023e': "T",    // Ⱦ  [LATIN CAPITAL LETTER T WITH DIAGONAL STROKE]
	'\u1d1b': "T",    // ᴛ  [LATIN LETTER SMALL CAPITAL T]
	'\u1e6a': "T",    // Ṫ  [LATIN CAPITAL LETTER T WITH DOT ABOVE]
	'\u1e6c': "T",    // Ṭ  [LATIN CAPITAL LETTER T WITH DOT BELOW]
	'\u1e6e': "T",    // Ṯ  [LATIN CAPITAL LETTER T WITH LINE BELOW]
	'\u1e70': "T",    // Ṱ  [LATIN CAPITAL LETTER T WITH CIRCUMFLEX BELOW]
	'\u24c9': "T",    // Ⓣ  [CIRCLED LATIN CAPITAL LETTER T]
	'\ua786': "T",    // Ꞇ  [LATIN CAPITAL LETTER INSULAR T]
	'\uff34': "T",    // Ｔ  [FULLWIDTH LATIN CAPITAL LETTER T]
	'\u0163': "t",    // ţ  [LATIN SMALL LETTER T WITH CEDILLA]
	'\u0165': "t",    // ť  [LATIN SMALL LETTER T WITH CARON]
	'\u0167': "t",    // ŧ  [LATIN SMALL LETTER T WITH STROKE]
	'\u01ab': "t",    // ƫ  [LATIN SMALL LETTER T WITH PALATAL HOOK]
	'\u01ad': "t",    // ƭ  [LATIN SMALL LETTER T WITH HOOK]
	'\u021b': "t",    // ț  [LATIN SMALL LETTER T WITH COMMA BELOW]
	'\u0236': "t",    // ȶ  [LATIN SMALL LETTER T WITH CURL]
	'\u0287': "t",    // ʇ  [LATIN SMALL LETTER TURNED T]
	'\u0288': "t",    // ʈ  [LATIN SMALL LETTER T WITH RETROFLEX HOOK]
	'\u1d75': "t",    // ᵵ  [LATIN SMALL LETTER T WITH MIDDLE TILDE]
	'\u1e6b': "t",    // ṫ  [LATIN SMALL LETTER T WITH DOT ABOVE]
	'\u1e6d': "t",    // ṭ  [LATIN SMALL LETTER T WITH DOT BELOW]
	'\u1e6f': "t",    // ṯ  [LATIN SMALL LETTER T WITH LINE BELOW]
	'\u1e71': "t",    // ṱ  [LATIN SMALL LETTER T WITH CIRCUMFLEX BELOW]
	'\u1e97': "t",    // ẗ  [LATIN SMALL LETTER T WITH DIAERESIS]
	'\u24e3': "t",    // ⓣ  [CIRCLED LATIN SMALL LETTER T]
	'\u2c66': "t",    // ⱦ  [LATIN SMALL LETTER T WITH DIAGONAL STROKE]
	'\uff54': "t",    // ｔ  [FULLWIDTH LATIN SMALL LETTER T]
	'\u00de': "TH",   // Þ  [LATIN CAPITAL LETTER THORN]
	'\ua766': "TH",   // Ꝧ  [LATIN CAPITAL LETTER THORN WITH STROKE THROUGH DESCENDER]
	'\ua728': "TZ",   // Ꜩ  [LATIN CAPITAL LETTER TZ]
	'\u24af': "(t)",  // ⒯  [PARENTHESIZED LATIN SMALL LETTER T]
	'\u02a8': "tc",   // ʨ  [LATIN SMALL LETTER TC DIGRAPH WITH CURL]
	'\u00fe': "th",   // þ  [LATIN SMALL LETTER THORN]
	'\u1d7a': "th",   // ᵺ  [LATIN SMALL LETTER TH WITH STRIKETHROUGH]
	'\ua767': "th",   // ꝧ  [LATIN SMALL LETTER THORN WITH STROKE THROUGH DESCENDER]
	'\u02a6': "ts",   // ʦ  [LATIN SMALL LETTER TS DIGRAPH]
	'\ua729': "tz",   // ꜩ  [LATIN SMALL LETTER TZ]
	'\u00d9': "U",    // Ù  [LATIN CAPITAL LETTER U WITH GRAVE]
	'\u00da': "U",    // Ú  [LATIN CAPITAL LETTER U WITH ACUTE]
	'\u00db': "U",    // Û  [LATIN CAPITAL LETTER U WITH CIRCUMFLEX]
	'\u00dc': "U",    // Ü  [LATIN CAPITAL LETTER U WITH DIAERESIS]
	'\u0168': "U",    // Ũ  [LATIN CAPITAL LETTER U WITH TILDE]
	'\u016a': "U",    // Ū  [LATIN CAPITAL LETTER U WITH MACRON]
	'\u016c': "U",    // Ŭ  [LATIN CAPITAL LETTER U WITH BREVE]
	'\u016e': "U",    // Ů  [LATIN CAPITAL LETTER U WITH RING ABOVE]
	'\u0170': "U",    // Ű  [LATIN CAPITAL LETTER U WITH DOUBLE ACUTE]
	'\u0172': "U",    // Ų  [LATIN CAPITAL LETTER U WITH OGONEK]
	'\u01af': "U",    // Ư  [LATIN CAPITAL LETTER U WITH HORN]
	'\u01d3': "U",    // Ǔ  [LATIN CAPITAL LETTER U WITH CARON]
	'\u01d5': "U",    // Ǖ  [LATIN CAPITAL LETTER U WITH DIAERESIS AND MACRON]
	'\u01d7': "U",    // Ǘ  [LATIN CAPITAL LETTER U WITH DIAERESIS AND ACUTE]
	'\u01d9': "U",    // Ǚ  [LATIN CAPITAL LETTER U WITH DIAERESIS AND CARON]
	'\u01db': "U",    // Ǜ  [LATIN CAPITAL LETTER U WITH DIAERESIS AND GRAVE]
	'\u0214': "U",    // Ȕ  [LATIN CAPITAL LETTER U WITH DOUBLE GRAVE]
	'\u0216': "U",    // Ȗ  [LATIN CAPITAL LETTER U WITH INVERTED BREVE]
	'\u0244': "U",    // Ʉ  [LATIN CAPITAL LETTER U BAR]
	'\u1d1c': "U",    // ᴜ  [LATIN LETTER SMALL CAPITAL U]
	'\u1d7e': "U",    // ᵾ  [LATIN SMALL CAPITAL LETTER U WITH STROKE]
	'\u1e72': "U",    // Ṳ  [LATIN CAPITAL LETTER U WITH DIAERESIS BELOW]
	'\u1e74': "U",    // Ṵ  [LATIN CAPITAL LETTER U WITH TILDE BELOW]
	'\u1e76': "U",    // Ṷ  [LATIN CAPITAL LETTER U WITH CIRCUMFLEX BELOW]
	'\u1e78': "U",    // Ṹ  [LATIN CAPITAL LETTER U WITH TILDE AND ACUTE]
	'\u1e7a': "U",    // Ṻ  [LATIN CAPITAL LETTER U WITH MACRON AND DIAERESIS]
	'\u1ee4': "U",    // Ụ  [LATIN CAPITAL LETTER U WITH DOT BELOW]
	'\u1ee6': "U",    // Ủ  [LATIN CAPITAL LETTER U WITH HOOK ABOVE]
	'\u1ee8': "U",    // Ứ  [LATIN CAPITAL LETTER U WITH HORN AND ACUTE]
	'\u1eea': "U",    // Ừ  [LATIN CAPITAL LETTER U WITH HORN AND GRAVE]
	'\u1eec': "U",    // Ử  [LATIN CAPITAL LETTER U WITH HORN AND HOOK ABOVE]
	'\u1eee': "U",    // Ữ  [LATIN CAPITAL LETTER U WITH HORN AND TILDE]
	'\u1ef0': "U",    // Ự  [LATIN CAPITAL LETTER U WITH HORN AND DOT BELOW]
	'\u24ca': "U",    // Ⓤ  [CIRCLED LATIN CAPITAL LETTER U]
	'\uff35': "U",    // Ｕ  [FULLWIDTH LATIN CAPITAL LETTER U]
	'\u00f9': "u",    // ù  [LATIN SMALL LETTER U WITH GRAVE]
	'\u00fa': "u",    // ú  [LATIN SMALL LETTER U WITH ACUTE]
	'\u00fb': "u",    // û  [LATIN SMALL LETTER U WITH CIRCUMFLEX]
	'\u00fc': "u",    // ü  [LATIN SMALL LETTER U WITH DIAERESIS]
	'\u0169': "u",    // ũ  [LATIN SMALL LETTER U WITH TILDE]
	'\u016b': "u",    // ū  [LATIN SMALL LETTER U WITH MACRON]
	'\u016d': "u",    // ŭ  [LATIN SMALL LETTER U WITH BREVE]
	'\u016f': "u",    // ů  [LATIN SMALL LETTER U WITH RING ABOVE]
	'\u0171': "u",    // ű  [LATIN SMALL LETTER U WITH DOUBLE ACUTE]
	'\u0173': "u",    // ų  [LATIN SMALL LETTER U WITH OGONEK]
	'\u01b0': "u",    // ư  [LATIN SMALL LETTER U WITH HORN]
	'\u01d4': "u",    // ǔ  [LATIN SMALL LETTER U WITH CARON]
	'\u01d6': "u",    // ǖ  [LATIN SMALL LETTER U WITH DIAERESIS AND MACRON]
	'\u01d8': "u",    // ǘ  [LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE]
	'\u01da': "u",    // ǚ  [LATIN SMALL LETTER U WITH DIAERESIS AND CARON]
	'\u01dc': "u",    // ǜ  [LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE]
	'\u0215': "u",    // ȕ  [LATIN SMALL LETTER U WITH DOUBLE GRAVE]
	'\u0217': "u",    // ȗ  [LATIN SMALL LETTER U WITH INVERTED BREVE]
	'\u0289': "u",    // ʉ  [LATIN SMALL LETTER U BAR]
	'\u1d64': "u",    // ᵤ  [LATIN SUBSCRIPT SMALL LETTER U]
	'\u1d99': "u",    // ᶙ  [LATIN SMALL LETTER U WITH RETROFLEX HOOK]
	'\u1e73': "u",    // ṳ  [LATIN SMALL LETTER U WITH DIAERESIS BELOW]
	'\u1e75': "u",    // ṵ  [LATIN SMALL LETTER U WITH TILDE BELOW]
	'\u1e77': "u",    // ṷ  [LATIN SMALL LETTER U WITH CIRCUMFLEX BELOW]
	'\u1e79': "u",    // ṹ  [LATIN SMALL LETTER U WITH TILDE AND ACUTE]
	'\u1e7b': "u",    // ṻ  [LATIN SMALL LETTER U WITH MACRON AND DIAERESIS]
	'\u1ee5': "u",    // ụ  [LATIN SMALL LETTER U WITH DOT BELOW]
	'\u1ee7': "u",    // ủ  [LATIN SMALL LETTER U WITH HOOK ABOVE]
	'\u1ee9': "u",    // ứ  [LATIN SMALL LETTER U WITH HORN AND ACUTE]
	'\u1eeb': "u",    // ừ  [LATIN SMALL LETTER U WITH HORN AND GRAVE]
	'\u1eed': "u",    // ử  [LATIN SMALL LETTER U WITH HORN AND HOOK ABOVE]
	'\u1eef': "u",    // ữ  [LATIN SMALL LETTER U WITH HORN AND TILDE]
	'\u1ef1': "u",    // ự  [LATIN SMALL LETTER U WITH HORN AND DOT BELOW]
	'\u24e4': "u",    // ⓤ  [CIRCLED LATIN SMALL LETTER U]
	'\uff55': "u",    // ｕ  [FULLWIDTH LATIN SMALL LETTER U]
	'\u24b0': "(u)",  // ⒰  [PARENTHESIZED LATIN SMALL LETTER U]
	'\u1d6b': "ue",   // ᵫ  [LATIN SMALL LETTER UE]
	'\u01b2': "V",    // Ʋ  [LATIN CAPITAL LETTER V WITH HOOK]
	'\u0245': "V",    // Ʌ  [LATIN CAPITAL LETTER TURNED V]
	'\u1d20': "V",    // ᴠ  [LATIN LETTER SMALL CAPITAL V]
	'\u1e7c': "V",    // Ṽ  [LATIN CAPITAL LETTER V WITH TILDE]
	'\u1e7e': "V",    // Ṿ  [LATIN CAPITAL LETTER V WITH DOT BELOW]
	'\u1efc': "V",    // Ỽ  [LATIN CAPITAL LETTER MIDDLE-WELSH V]
	'\u24cb': "V",    // Ⓥ  [CIRCLED LATIN CAPITAL LETTER V]
	'\ua75e': "V",    // Ꝟ  [LATIN CAPITAL LETTER V WITH DIAGONAL STROKE]
	'\ua768': "V",    // Ꝩ  [LATIN CAPITAL LETTER VEND]
	'\uff36': "V",    // Ｖ  [FULLWIDTH LATIN CAPITAL LETTER V]
	'\u028b': "v",    // ʋ  [LATIN SMALL LETTER V WITH HOOK]
	'\u028c': "v",    // ʌ  [LATIN SMALL LETTER TURNED V]
	'\u1d65': "v",    // ᵥ  [LATIN SUBSCRIPT SMALL LETTER V]
	'\u1d8c': "v",    // ᶌ  [LATIN SMALL LETTER V WITH PALATAL HOOK]
	'\u1e7d': "v",    // ṽ  [LATIN SMALL LETTER V WITH TILDE]
	'\u1e7f': "v",    // ṿ  [LATIN SMALL LETTER V WITH DOT BELOW]
	'\u24e5': "v",    // ⓥ  [CIRCLED LATIN SMALL LETTER V]
	'\u2c71': "v",    // ⱱ  [LATIN SMALL LETTER V WITH RIGHT HOOK]
	'\u2c74': "v",    // ⱴ  [LATIN SMALL LETTER V WITH CURL]
	'\ua75f': "v",    // ꝟ  [LATIN SMALL LETTER V WITH DIAGONAL STROKE]
	'\uff56': "v",    // ｖ  [FULLWIDTH LATIN SMALL LETTER V]
	'\ua760': "VY",   // Ꝡ  [LATIN CAPITAL LETTER VY]
	'\u24b1': "(v)",  // ⒱  [PARENTHESIZED LATIN SMALL LETTER V]
	'\ua761': "vy",   // ꝡ  [LATIN SMALL LETTER VY]
	'\u0174': "W",    // Ŵ  [LATIN CAPITAL LETTER W WITH CIRCUMFLEX]
	'\u01f7': "W",    // Ƿ  http://en.wikipedia.org/wiki/Wynn  [LATIN CAPITAL LETTER WYNN]
	'\u1d21': "W",    // ᴡ  [LATIN LETTER SMALL CAPITAL W]
	'\u1e80': "W",    // Ẁ  [LATIN CAPITAL LETTER W WITH GRAVE]
	'\u1e82': "W",    // Ẃ  [LATIN CAPITAL LETTER W WITH ACUTE]
	'\u1e84': "W",    // Ẅ  [LATIN CAPITAL LETTER W WITH DIAERESIS]
	'\u1e86': "W",    // Ẇ  [LATIN CAPITAL LETTER W WITH DOT ABOVE]
	'\u1e88': "W",    // Ẉ  [LATIN CAPITAL LETTER W WITH DOT BELOW]
	'\u24cc': "W",    // Ⓦ  [CIRCLED LATIN CAPITAL LETTER W]
	'\u2c72': "W",    // Ⱳ  [LATIN CAPITAL LETTER W WITH HOOK]
	'\uff37': "W",    // Ｗ  [FULLWIDTH LATIN CAPITAL LETTER W]
	'\u0175': "w",    // ŵ  [LATIN SMALL LETTER W WITH CIRCUMFLEX]
	'\u01bf': "w",    // ƿ  http://en.wikipedia.org/wiki/Wynn  [LATIN LETTER WYNN]
	'\u028d': "w",    // ʍ  [LATIN SMALL LETTER TURNED W]
	'\u1e81': "w",    // ẁ  [LATIN SMALL LETTER W WITH GRAVE]
	'\u1e83': "w",    // ẃ  [LATIN SMALL LETTER W WITH ACUTE]
	'\u1e85': "w",    // ẅ  [LATIN SMALL LETTER W WITH DIAERESIS]
	'\u1e87': "w",    // ẇ  [LATIN SMALL LETTER W WITH DOT ABOVE]
	'\u1e89': "w",    // ẉ  [LATIN SMALL LETTER W WITH DOT BELOW]
	'\u1e98': "w",    // ẘ  [LATIN SMALL LETTER W WITH RING ABOVE]
	'\u24e6': "w",    // ⓦ  [CIRCLED LATIN SMALL LETTER W]
	'\u2c73': "w",    // ⱳ  [LATIN SMALL LETTER W WITH HOOK]
	'\uff57': "w",    // ｗ  [FULLWIDTH LATIN SMALL LETTER W]
	'\u24b2': "(w)",  // ⒲  [PARENTHESIZED LATIN SMALL LETTER W]
	'\u1e8a': "X",    // Ẋ  [LATIN CAPITAL LETTER X WITH DOT ABOVE]
	'\u1e8c': "X",    // Ẍ  [LATIN CAPITAL LETTER X WITH DIAERESIS]
	'\u24cd': "X",    // Ⓧ  [CIRCLED LATIN CAPITAL LETTER X]
	'\uff38': "X",    // Ｘ  [FULLWIDTH LATIN CAPITAL LETTER X]
	'\u1d8d': "x",    // ᶍ  [LATIN SMALL LETTER X WITH PALATAL HOOK]
	'\u1e8b': "x",    // ẋ  [LATIN SMALL LETTER X WITH DOT ABOVE]
	'\u1e8d': "x",    // ẍ  [LATIN SMALL LETTER X WITH DIAERESIS]
	'\u2093': "x",    // ₓ  [LATIN SUBSCRIPT SMALL LETTER X]
	'\u24e7': "x",    // ⓧ  [CIRCLED LATIN SMALL LETTER X]
	'\uff58': "x",    // ｘ  [FULLWIDTH LATIN SMALL LETTER X]
	'\u24b3': "(x)",  // ⒳  [PARENTHESIZED LATIN SMALL LETTER X]
	'\u00dd': "Y",    // Ý  [LATIN CAPITAL LETTER Y WITH ACUTE]
	'\u0176': "Y",    // Ŷ  [LATIN CAPITAL LETTER Y WITH CIRCUMFLEX]
	'\u0178': "Y",    // Ÿ  [LATIN CAPITAL LETTER Y WITH DIAERESIS]
	'\u01b3': "Y",    // Ƴ  [LATIN CAPITAL LETTER Y WITH HOOK]
	'\u0232': "Y",    // Ȳ  [LATIN CAPITAL LETTER Y WITH MACRON]
	'\u024e': "Y",    // Ɏ  [LATIN CAPITAL LETTER Y WITH STROKE]
	'\u028f': "Y",    // ʏ  [LATIN LETTER SMALL CAPITAL Y]
	'\u1e8e': "Y",    // Ẏ  [LATIN CAPITAL LETTER Y WITH DOT ABOVE]
	'\u1ef2': "Y",    // Ỳ  [LATIN CAPITAL LETTER Y WITH GRAVE]
	'\u1ef4': "Y",    // Ỵ  [LATIN CAPITAL LETTER Y WITH DOT BELOW]
	'\u1ef6': "Y",    // Ỷ  [LATIN CAPITAL LETTER Y WITH HOOK ABOVE]
	'\u1ef8': "Y",    // Ỹ  [LATIN CAPITAL LETTER Y WITH TILDE]
	'\u1efe': "Y",    // Ỿ  [LATIN CAPITAL LETTER Y WITH LOOP]
	'\u24ce': "Y",    // Ⓨ  [CIRCLED LATIN CAPITAL LETTER Y]
	'\uff39': "Y",    // Ｙ  [FULLWIDTH LATIN CAPITAL LETTER Y]
	'\u00fd': "y",    // ý  [LATIN SMALL LETTER Y WITH ACUTE]
	'\u00ff': "y",    // ÿ  [LATIN SMALL LETTER Y WITH DIAERESIS]
	'\u0177': "y",    // ŷ  [LATIN SMALL LETTER Y WITH CIRCUMFLEX]
	'\u01b4': "y",    // ƴ  [LATIN SMALL LETTER Y WITH HOOK]
	'\u0233': "y",    // ȳ  [LATIN SMALL LETTER Y WITH MACRON]
	'\u024f': "y",    // ɏ  [LATIN SMALL LETTER Y WITH STROKE]
	'\u028e': "y",    // ʎ  [LATIN SMALL LETTER TURNED Y]
	'\u1e8f': "y",    // ẏ  [LATIN SMALL LETTER Y WITH DOT ABOVE]
	'\u1e99': "y",    // ẙ  [LATIN SMALL LETTER Y WITH RING ABOVE]
	'\u1ef3': "y",    // ỳ  [LATIN SMALL LETTER Y WITH GRAVE]
	'\u1ef5': "y",    // ỵ  [LATIN SMALL LETTER Y WITH DOT BELOW]
	'\u1ef7': "y",    // ỷ  [LATIN SMALL LETTER Y WITH HOOK ABOVE]
	'\u1ef9': "y",    // ỹ  [LATIN SMALL LETTER Y WITH TILDE]
	'\u1eff': "y",    // ỿ  [LATIN SMALL LETTER Y WITH LOOP]
	'\u24e8': "y",    // ⓨ  [CIRCLED LATIN SMALL LETTER Y]
	'\uff59': "y",    // ｙ  [FULLWIDTH LATIN SMALL LETTER Y]
	'\u24b4': "(y)",  // ⒴  [PARENTHESIZED LATIN SMALL LETTER Y]
	'\u0179': "Z",    // Ź  [LATIN CAPITAL LETTER Z WITH ACUTE]
	'\u017b': "Z",    // Ż  [LATIN CAPITAL LETTER Z WITH DOT ABOVE]
	'\u017d': "Z",    // Ž  [LATIN CAPITAL LETTER Z WITH CARON]
	'\u01b5': "Z",    // Ƶ  [LATIN CAPITAL LETTER Z WITH STROKE]
	'\u021c': "Z",    // Ȝ  http://en.wikipedia.org/wiki/Yogh  [LATIN CAPITAL LETTER YOGH]
	'\u0224': "Z",    // Ȥ  [LATIN CAPITAL LETTER Z WITH HOOK]
	'\u1d22': "Z",    // ᴢ  [LATIN LETTER SMALL CAPITAL Z]
	'\u1e90': "Z",    // Ẑ  [LATIN CAPITAL LETTER Z WITH CIRCUMFLEX]
	'\u1e92': "Z",    // Ẓ  [LATIN CAPITAL LETTER Z WITH DOT BELOW]
	'\u1e94': "Z",    // Ẕ  [LATIN CAPITAL LETTER Z WITH LINE BELOW]
	'\u24cf': "Z",    // Ⓩ  [CIRCLED LATIN CAPITAL LETTER Z]
	'\u2c6b': "Z",    // Ⱬ  [LATIN CAPITAL LETTER Z WITH DESCENDER]
	'\ua762': "Z",    // Ꝣ  [LATIN CAPITAL LETTER VISIGOTHIC Z]
	'\uff3a': "Z",    // Ｚ  [FULLWIDTH LATIN CAPITAL LETTER Z]
	'\u017a': "z",    // ź  [LATIN SMALL LETTER Z WITH ACUTE]
	'\u017c': "z",    // ż  [LATIN SMALL LETTER Z WITH DOT ABOVE]
	'\u017e': "z",    // ž  [LATIN SMALL LETTER Z WITH CARON]
	'\u01b6': "z",    // ƶ  [LATIN SMALL LETTER Z WITH STROKE]
	'\u021d': "z",    // ȝ  http://en.wikipedia.org/wiki/Yogh  [LATIN SMALL LETTER YOGH]
	'\u0225': "z",    // ȥ  [LATIN SMALL LETTER Z WITH HOOK]
	'\u0240': "z",    // ɀ  [LATIN SMALL LETTER Z WITH SWASH TAIL]
	'\u0290': "z",    // ʐ  [LATIN SMALL LETTER Z WITH RETROFLEX HOOK]
	'\u0291': "z",    // ʑ  [LATIN SMALL LETTER Z WITH CURL]
	'\u1d76': "z",    // ᵶ  [LATIN SMALL LETTER Z WITH MIDDLE TILDE]
	'\u1d8e': "z",    // ᶎ  [LATIN SMALL LETTER Z WITH PALATAL HOOK]
	'\u1e91': "z",    // ẑ  [LATIN SMALL LETTER Z WITH CIRCUMFLEX]
	'\u1e93': "z",    // ẓ  [LATIN SMALL LETTER Z WITH DOT BELOW]
	'\u1e95': "z",    // ẕ  [LATIN SMALL LETTER Z WITH LINE BELOW]
	'\u24e9': "z",    // ⓩ  [CIRCLED LATIN SMALL LETTER Z]
	'\u2c6c': "z",    // ⱬ  [LATIN SMALL LETTER Z WITH DESCENDER]
	'\ua763': "z",    // ꝣ  [LATIN SMALL LETTER VISIGOTHIC Z]
	'\uff5a': "z",    // ｚ  [FULLWIDTH LATIN SMALL LETTER Z]
	'\u24b5': "(z)",  // ⒵  [PARENTHESIZED LATIN SMALL LETTER Z]
	'\u2070': "0",    // ⁰  [SUPERSCRIPT ZERO]
	'\u2080': "0",    // ₀  [SUBSCRIPT ZERO]
	'\u24ea': "0",    // ⓪  [CIRCLED DIGIT ZERO]
	'\u24ff': "0",    // ⓿  [NEGATIVE CIRCLED DIGIT ZERO]
	'\uff10': "0",    // ０  [FULLWIDTH DIGIT ZERO]
	'\u00b9': "1",    // ¹  [SUPERSCRIPT ONE]
	'\u2081': "1",    // ₁  [SUBSCRIPT ONE]
	'\u2460': "1",    // ①  [CIRCLED DIGIT ONE]
	'\u24f5': "1",    // ⓵  [DOUBLE CIRCLED DIGIT ONE]
	'\u2776': "1",    // ❶  [DINGBAT NEGATIVE CIRCLED DIGIT ONE]
	'\u2780': "1",    // ➀  [DINGBAT CIRCLED SANS-SERIF DIGIT ONE]
	'\u278a': "1",    // ➊  [DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT ONE]
	'\uff11': "1",    // １  [FULLWIDTH DIGIT ONE]
	'\u2488': "1.",   // ⒈  [DIGIT ONE FULL STOP]
	'\u2474': "(1)",  // ⑴  [PARENTHESIZED DIGIT ONE]
	'\u00b2': "2",    // ²  [SUPERSCRIPT TWO]
	'\u2082': "2",    // ₂  [SUBSCRIPT TWO]
	'\u2461': "2",    // ②  [CIRCLED DIGIT TWO]
	'\u24f6': "2",    // ⓶  [DOUBLE CIRCLED DIGIT TWO]
	'\u2777': "2",    // ❷  [DINGBAT NEGATIVE CIRCLED DIGIT TWO]
	'\u2781': "2",    // ➁  [DINGBAT CIRCLED SANS-SERIF DIGIT TWO]
	'\u278b': "2",    // ➋  [DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT TWO]
	'\uff12': "2",    // ２  [FULLWIDTH DIGIT TWO]
	'\u2489': "2.",   // ⒉  [DIGIT TWO FULL STOP]
	'\u2475': "(2)",  // ⑵  [PARENTHESIZED DIGIT TWO]
	'\u00b3': "3",    // ³  [SUPERSCRIPT THREE]
	'\u2083': "3",    // ₃  [SUBSCRIPT THREE]
	'\u2462': "3",    // ③  [CIRCLED DIGIT THREE]
	'\u24f7': "3",    // ⓷  [DOUBLE CIRCLED DIGIT THREE]
	'\u2778': "3",    // ❸  [DINGBAT NEGATIVE CIRCLED DIGIT THREE]
	'\u2782': "3",    // ➂  [DINGBAT CIRCLED SANS-SERIF DIGIT THREE]
	'\u278c': "3",    // ➌  [DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT THREE]
	'\uff13': "3",    // ３  [FULLWIDTH DIGIT THREE]
	'\u248a': "3.",   // ⒊  [DIGIT THREE FULL STOP]
	'\u2476': "(3)",  // ⑶  [PARENTHESIZED DIGIT THREE]
	'\u2074': "4",    // ⁴  [SUPERSCRIPT FOUR]
	'\u2084': "4",    // ₄  [SUBSCRIPT FOUR]
	'\u2463': "4",    // ④  [CIRCLED DIGIT FOUR]
	'\u24f8': "4",    // ⓸  [DOUBLE CIRCLED DIGIT FOUR]
	'\u2779': "4",    // ❹  [DINGBAT NEGATIVE CIRCLED DIGIT FOUR]
	'\u2783': "4",    // ➃  [DINGBAT CIRCLED SANS-SERIF DIGIT FOUR]
	'\u278d': "4",    // ➍  [DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT FOUR]
	'\uff14': "4",    // ４  [FULLWIDTH DIGIT FOUR]
	'\u248b': "4.",   // ⒋  [DIGIT FOUR FULL STOP]
	'\u2477': "(4)",  // ⑷  [PARENTHESIZED DIGIT FOUR]
	'\u2075': "5",    // ⁵  [SUPERSCRIPT FIVE]
	'\u2085': "5",    // ₅  [SUBSCRIPT FIVE]
	'\u2464': "5",    // ⑤  [CIRCLED DIGIT FIVE]
	'\u24f9': "5",    // ⓹  [DOUBLE CIRCLED DIGIT FIVE]
	'\u277a': "5",    // ❺  [DINGBAT NEGATIVE CIRCLED DIGIT FIVE]
	'\u2784': "5",    // ➄  [DINGBAT CIRCLED SANS-SERIF DIGIT FIVE]
	'\u278e': "5",    // ➎  [DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT FIVE]
	'\uff15': "5",    // ５  [FULLWIDTH DIGIT FIVE]
	'\u248c': "5.",   // ⒌  [DIGIT FIVE FULL STOP]
	'\u2478': "(5)",  // ⑸  [PARENTHESIZED DIGIT FIVE]
	'\u2076': "6",    // ⁶  [SUPERSCRIPT SIX]
	'\u2086': "6",    // ₆  [SUBSCRIPT SIX]
	'\u2465': "6",    // ⑥  [CIRCLED DIGIT SIX]
	'\u24fa': "6",    // ⓺  [DOUBLE CIRCLED DIGIT SIX]
	'\u277b': "6",    // ❻  [DINGBAT NEGATIVE CIRCLED DIGIT SIX]
	'\u2785': "6",    // ➅  [DINGBAT CIRCLED SANS-SERIF DIGIT SIX]
	'\u278f': "6",    // ➏  [DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT SIX]
	'\uff16': "6",    // ６  [FULLWIDTH DIGIT SIX]
	'\u248d': "6.",   // ⒍  [DIGIT SIX FULL STOP]
	'\u2479': "(6)",  // ⑹  [PARENTHESIZED DIGIT SIX]
	'\u2077': "7",    // ⁷  [SUPERSCRIPT SEVEN]
	'\u2087': "7",    // ₇  [SUBSCRIPT SEVEN]
	'\u2466': "7",    // ⑦  [CIRCLED DIGIT SEVEN]
	'\u24fb': "7",    // ⓻  [DOUBLE CIRCLED DIGIT SEVEN]
	'\u277c': "7",    // ❼  [DINGBAT NEGATIVE CIRCLED DIGIT SEVEN]
	'\u2786': "7",    // ➆  [DINGBAT CIRCLED SANS-SERIF DIGIT SEVEN]
	'\u2790': "7",    // ➐  [DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT SEVEN]
	'\uff17': "7",    // ７  [FULLWIDTH DIGIT SEVEN]
	'\u248e': "7.",   // ⒎  [DIGIT SEVEN FULL STOP]
	'\u247a': "(7)",  // ⑺  [PARENTHESIZED DIGIT SEVEN]
	'\u2078': "8",    // ⁸  [SUPERSCRIPT EIGHT]
	'\u2088': "8",    // ₈  [SUBSCRIPT EIGHT]
	'\u2467': "8",    // ⑧  [CIRCLED DIGIT EIGHT]
	'\u24fc': "8",    // ⓼  [DOUBLE CIRCLED DIGIT EIGHT]
	'\u277d': "8",    // ❽  [DINGBAT NEGATIVE CIRCLED DIGIT EIGHT]
	'\u2787': "8",    // ➇  [DINGBAT CIRCLED SANS-SERIF DIGIT EIGHT]
	'\u2791': "8",    // ➑  [DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT EIGHT]
	'\uff18': "8",    // ８  [FULLWIDTH DIGIT EIGHT]
	'\u248f': "8.",   // ⒏  [DIGIT EIGHT FULL STOP]
	'\u247b': "(8)",  // ⑻  [PARENTHESIZED DIGIT EIGHT]
	'\u2079': "9",    // ⁹  [SUPERSCRIPT NINE]
	'\u2089': "9",    // ₉  [SUBSCRIPT NINE]
	'\u2468': "9",    // ⑨  [CIRCLED DIGIT NINE]
	'\u24fd': "9",    // ⓽  [DOUBLE CIRCLED DIGIT NINE]
	'\u277e': "9",    // ❾  [DINGBAT NEGATIVE CIRCLED DIGIT NINE]
	'\u2788': "9",    // ➈  [DINGBAT CIRCLED SANS-SERIF DIGIT NINE]
	'\u2792': "9",    // ➒  [DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT NINE]
	'\uff19': "9",    // ９  [FULLWIDTH DIGIT NINE]
	'\u2490': "9.",   // ⒐  [DIGIT NINE FULL STOP]
	'\u247c': "(9)",  // ⑼  [PARENTHESIZED DIGIT NINE]
	'\u2469': "10",   // ⑩  [CIRCLED NUMBER TEN]
	'\u24fe': "10",   // ⓾  [DOUBLE CIRCLED NUMBER TEN]
	'\u277f': "10",   // ❿  [DINGBAT NEGATIVE CIRCLED NUMBER TEN]
	'\u2789': "10",   // ➉  [DINGBAT CIRCLED SANS-SERIF NUMBER TEN]
	'\u2793': "10",   // ➓  [DINGBAT NEGATIVE CIRCLED SANS-SERIF NUMBER TEN]
	'\u2491': "10.",  // ⒑  [NUMBER TEN FULL STOP]
	'\u247d': "(10)", // ⑽  [PARENTHESIZED NUMBER TEN]
	'\u246a': "11",   // ⑪  [CIRCLED NUMBER ELEVEN]
	'\u24eb': "11",   // ⓫  [NEGATIVE CIRCLED NUMBER ELEVEN]
	'\u2492': "11.",  // ⒒  [NUMBER ELEVEN FULL STOP]
	'\u247e': "(11)", // ⑾  [PARENTHESIZED NUMBER ELEVEN]
	'\u246b': "12",   // ⑫  [CIRCLED NUMBER TWELVE]
	'\u24ec': "12",   // ⓬  [NEGATIVE CIRCLED NUMBER TWELVE]
	'\u2493': "12.",  // ⒓  [NUMBER TWELVE FULL STOP]
	'\u247f': "(12)", // ⑿  [PARENTHESIZED NUMBER TWELVE]
	'\u246c': "13",   // ⑬  [CIRCLED NUMBER THIRTEEN]
	'\u24ed': "13",   // ⓭  [NEGATIVE CIRCLED NUMBER THIRTEEN]
	'\u2494': "13.",  // ⒔  [NUMBER THIRTEEN FULL STOP]
	'\u2480': "(13)", // ⒀  [PARENTHESIZED NUMBER THIRTEEN]
	'\u246d': "14",   // ⑭  [CIRCLED NUMBER FOURTEEN]
	'\u24ee': "14",   // ⓮  [NEGATIVE CIRCLED NUMBER FOURTEEN]
	'\u2495': "14.",  // ⒕  [NUMBER FOURTEEN FULL STOP]
	'\u2481': "(14)", // ⒁  [PARENTHESIZED NUMBER FOURTEEN]
	'\u246e': "15",   // ⑮  [CIRCLED NUMBER FIFTEEN]
	'\u24ef': "15",   // ⓯  [NEGATIVE CIRCLED NUMBER FIFTEEN]
	'\u2496': "15.",  // ⒖  [NUMBER FIFTEEN FULL STOP]
	'\u2482': "(15)", // ⒂  [PARENTHESIZED NUMBER FIFTEEN]
	'\u246f': "16",   // ⑯  [CIRCLED NUMBER SIXTEEN]
	'\u24f0': "16",   // ⓰  [NEGATIVE CIRCLED NUMBER SIXTEEN]
	'\u2497': "16.",  // ⒗  [NUMBER SIXTEEN FULL STOP]
	'\u2483': "(16)", // ⒃  [PARENTHESIZED NUMBER SIXTEEN]
	'\u2470': "17",   // ⑰  [CIRCLED NUMBER SEVENTEEN]
	'\u24f1': "17",   // ⓱  [NEGATIVE CIRCLED NUMBER SEVENTEEN]
	'\u2498': "17.",  // ⒘  [NUMBER SEVENTEEN FULL STOP]
	'\u2484': "(17)", // ⒄  [PARENTHESIZED NUMBER SEVENTEEN]
	'\u2471': "18",   // ⑱  [CIRCLED NUMBER EIGHTEEN]
	'\u24f2': "18",   // ⓲  [NEGATIVE CIRCLED NUMBER EIGHTEEN]
	'\u2499': "18.",  // ⒙  [NUMBER EIGHTEEN FULL STOP]
	'\u2485': "(18)", // ⒅  [PARENTHESIZED NUMBER EIGHTEEN]
	'\u2472': "19",   // ⑲  [CIRCLED NUMBER NINETEEN]
	'\u24f3': "19",   // ⓳  [NEGATIVE CIRCLED NUMBER NINETEEN]
	'\u249a': "19.",  // ⒚  [NUMBER NINETEEN FULL STOP]
	'\u2486': "(19)", // ⒆  [PARENTHESIZED NUMBER NINETEEN]
	'\u2473': "20",   // ⑳  [CIRCLED NUMBER TWENTY]
	'\u24f4': "20",   // ⓴  [NEGATIVE CIRCLED NUMBER TWENTY]
	'\u249b': "20.",  // ⒛  [NUMBER TWENTY FULL STOP]
	'\u2487': "(20)", // ⒇  [PARENTHESIZED NUMBER TWENTY]
	'\u00ab': "\"",   // «  [LEFT-POINTING DOUBLE ANGLE QUOTATION MARK]
	'\u00bb': "\"",   // »  [RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK]
	'\u201c': "\"",   // “  [LEFT DOUBLE QUOTATION MARK]
	'\u201d': "\"",   // ”  [RIGHT DOUBLE QUOTATION MARK]
	'\u201e': "\"",   // „  [DOUBLE LOW-9 QUOTATION MARK]
	'\u2033': "\"",   // ″  [DOUBLE PRIME]
	'\u2036': "\"",   // ‶  [REVERSED DOUBLE PRIME]
	'\u275d': "\"",   // ❝  [HEAVY DOUBLE TURNED COMMA QUOTATION MARK ORNAMENT]
	'\u275e': "\"",   // ❞  [HEAVY DOUBLE COMMA QUOTATION MARK ORNAMENT]
	'\u276e': "\"",   // ❮  [HEAVY LEFT-POINTING ANGLE QUOTATION MARK ORNAMENT]
	'\u276f': "\"",   // ❯  [HEAVY RIGHT-POINTING ANGLE QUOTATION MARK ORNAMENT]
	'\uff02': "\"",   // ＂  [FULLWIDTH QUOTATION MARK]
	'\u2018': "'",    // ‘  [LEFT SINGLE QUOTATION MARK]
	'\u2019': "'",    // ’  [RIGHT SINGLE QUOTATION MARK]
	'\u201a': "'",    // ‚  [SINGLE LOW-9 QUOTATION MARK]
	'\u201b': "'",    // ‛  [SINGLE HIGH-REVERSED-9 QUOTATION MARK]
	'\u2032': "'",    // ′  [PRIME]
	'\u2035': "'",    // ‵  [REVERSED PRIME]
	'\u2039': "'",    // ‹  [SINGLE LEFT-POINTING ANGLE QUOTATION MARK]
	'\u203a': "'",    // ›  [SINGLE RIGHT-POINTING ANGLE QUOTATION MARK]
	'\u275b': "'",    // ❛  [HEAVY SINGLE TURNED COMMA QUOTATION MARK ORNAMENT]
	'\u275c': "'",    // ❜  [HEAVY SINGLE COMMA QUOTATION MARK ORNAMENT]
	'\uff07': "'",    // ＇  [FULLWIDTH APOSTROPHE]
	'\u2010': "-",    // ‐  [HYPHEN]
	'\u2011': "-",    // ‑  [NON-BREAKING HYPHEN]
	'\u2012': "-",    // ‒  [FIGURE DASH]
	'\u2013': "-",    // –  [EN DASH]
	'\u2014': "-",    // —  [EM DASH]
	'\u207b': "-",    // ⁻  [SUPERSCRIPT MINUS]
	'\u208b': "-",    // ₋  [SUBSCRIPT MINUS]
	'\uff0d': "-",    // －  [FULLWIDTH HYPHEN-MINUS]
	'\u2045': "[",    // ⁅  [LEFT SQUARE BRACKET WITH QUILL]
	'\u2772': "[",    // ❲  [LIGHT LEFT TORTOISE SHELL BRACKET ORNAMENT]
	'\uff3b': "[",    // ［  [FULLWIDTH LEFT SQUARE BRACKET]
	'\u2046': "]",    // ⁆  [RIGHT SQUARE BRACKET WITH QUILL]
	'\u2773': "]",    // ❳  [LIGHT RIGHT TORTOISE SHELL BRACKET ORNAMENT]
	'\uff3d': "]",    // ］  [FULLWIDTH RIGHT SQUARE BRACKET]
	'\u207d': "(",    // ⁽  [SUPERSCRIPT LEFT PARENTHESIS]
	'\u208d': "(",    // ₍  [SUBSCRIPT LEFT PARENTHESIS]
	'\u2768': "(",    // ❨  [MEDIUM LEFT PARENTHESIS ORNAMENT]
	'\u276a': "(",    // ❪  [MEDIUM FLATTENED LEFT PARENTHESIS ORNAMENT]
	'\uff08': "(",    // （  [FULLWIDTH LEFT PARENTHESIS]
	'\u2e28': "((",   // ⸨  [LEFT DOUBLE PARENTHESIS]
	'\u207e': ")",    // ⁾  [SUPERSCRIPT RIGHT PARENTHESIS]
	'\u208e': ")",    // ₎  [SUBSCRIPT RIGHT PARENTHESIS]
	'\u2769': ")",    // ❩  [MEDIUM RIGHT PARENTHESIS ORNAMENT]
	'\u276b': ")",    // ❫  [MEDIUM FLATTENED RIGHT PARENTHESIS ORNAMENT]
	'\uff09': ")",    // ）  [FULLWIDTH RIGHT PARENTHESIS]
	'\u2e29': "))",   // ⸩  [RIGHT DOUBLE PARENTHESIS]
	'\u276c': "<",    // ❬  [MEDIUM LEFT-POINTING ANGLE BRACKET ORNAMENT]
	'\u2770': "<",    // ❰  [HEAVY LEFT-POINTING ANGLE BRACKET ORNAMENT]
	'\uff1c': "<",    // ＜  [FULLWIDTH LESS-THAN SIGN]
	'\u276d': ">",    // ❭  [MEDIUM RIGHT-POINTING ANGLE BRACKET ORNAMENT]
	'\u2771': ">",    // ❱  [HEAVY RIGHT-POINTING ANGLE BRACKET ORNAMENT]
	'\uff1e': ">",    // ＞  [FULLWIDTH GREATER-THAN SIGN]
	'\u2774': "{",    // ❴  [MEDIUM LEFT CURLY BRACKET ORNAMENT]
	'\uff5b': "{",    // ｛  [FULLWIDTH LEFT CURLY BRACKET]
	'\u2775': "}",    // ❵  [MEDIUM RIGHT CURLY BRACKET ORNAMENT]
	'\uff5d': "}",    // ｝  [FULLWIDTH RIGHT CURLY BRACKET]
	'\u207a': "+",    // ⁺  [SUPERSCRIPT PLUS SIGN]
	'\u208a': "+",    // ₊  [SUBSCRIPT PLUS SIGN]
	'\uff0b': "+",    // ＋  [FULLWIDTH PLUS SIGN]
	'\u207c': "=",    // ⁼  [SUPERSCRIPT EQUALS SIGN]
	'\u208c': "=",    // ₌  [SUBSCRIPT EQUALS SIGN]
	'\uff1d': "=",    // ＝  [FULLWIDTH EQUALS SIGN]
	'\uff01': "!",    // ！  [FULLWIDTH EXCLAMATION MARK]
	'\u203c': "!!",   // ‼  [DOUBLE EXCLAMATION MARK]
	'\u2049': "!?",   // ⁉  [EXCLAMATION QUESTION MARK]
	'\uff03': "#",    // ＃  [FULLWIDTH NUMBER SIGN]
	'\uff04': "$",    // ＄  [FULLWIDTH DOLLAR SIGN]
	'\u2052': "%",    // ⁒  [COMMERCIAL MINUS SIGN]
	'\uff05': "%",    // ％  [FULLWIDTH PERCENT SIGN]
	'\uff06': "&",    // ＆  [FULLWIDTH AMPERSAND]
	'\u204e': "*",    // ⁎  [LOW ASTERISK]
	'\uff0a': "*",    // ＊  [FULLWIDTH ASTERISK]
	'\uff0c': ",",    // ，  [FULLWIDTH COMMA]
	'\uff0e': ".",    // ．  [FULLWIDTH FULL STOP]
	'\u2044': "/",    // ⁄  [FRACTION SLASH]
	'\uff0f': "/",    // ／  [FULLWIDTH SOLIDUS]
	'\uff1a': ":",    // ：  [FULLWIDTH COLON]
	'\u204f': ";",    // ⁏  [REVERSED SEMICOLON]
	'\uff1b': ";",    // ；  [FULLWIDTH SEMICOLON]
	'\uff1f': "?",    // ？  [FULLWIDTH QUESTION MARK]
	'\u2047': "??",   // ⁇  [DOUBLE QUESTION MARK]
	'\u2048': "?!",   // ⁈  [QUESTION EXCLAMATION MARK]
	'\uff20': "@",    // ＠  [FULLWIDTH COMMERCIAL AT]
	'\uff3c': "\\",   // ＼  [FULLWIDTH REVERSE SOLIDUS]
	'\u2038': "^",    // ‸  [CARET]
	'\uff3e': "^",    // ＾  [FULLWIDTH CIRCUMFLEX ACCENT]
	'\uff3f': "_",    // ＿  [FULLWIDTH LOW LINE]
}
